dindri/dindri/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from home import views as home_views

urlpatterns = [
   url(r'^$', home_views.home, name='home'),
   url(r'^relacionamento/', include('relacionamento.urls')),
   url(r'^vendas/', include('vendas.urls')),
   url(r'^compras/', include('compras.urls')),
   url(r'^estoque/', include('estoque.urls')),
   url(r'^producao/', include('producao.urls')),
   url(r'^receitas/', include('receitas.urls')),
   url(r'^admin/', admin.site.urls),
]

dindri/home/urls.py
from django.conf.urls import url
from django.contrib import admin
from home import views as home_views

urlpatterns = [
   url(r'^$', home_views.home, name='home_page'),
]

dindri/vendas/urls.py
from django.conf.urls import url
from vendas.views import VendasHomeView, \
   TipoContatoListView, TipoContatoCreateView, TipoContatoDeleteView, TipoContatoDetailView, TipoContatoUpdateView, \
   VendaListView, VendaCreateView, VendaDeleteView, VendaDetailView, VendaUpdateView, \
   ReposicaoListView, ReposicaoCreateView, ReposicaoDeleteView, ReposicaoDetailView, ReposicaoUpdateView

urlpatterns = [
   ###  vendas
   url(r'^$', VendasHomeView.as_view(), name='vendas_home'),
   ###  venda
   url(r'^venda/lista/$', VendaListView.as_view(), name='venda_list'),
   url(r'^venda/novo/$', VendaCreateView.as_view(), name='venda_create'),
   url(r'^venda/detalha(?P<pk>\d+)$', VendaDetailView.as_view(), name='venda_detail'),
   url(r'^venda/edita/(?P<pk>\d+)$', VendaUpdateView.as_view(), name='venda_update'),
   url(r'^venda/exclui/(?P<pk>\d+)$', VendaDeleteView.as_view(), name='venda_delete'),
   ###  tipo_contato
   url(r'^tipo_contato/lista/$', TipoContatoListView.as_view(), name='tipo_contato_list'),
   url(r'^tipo_contato/novo/$', TipoContatoCreateView.as_view(), name='tipo_contato_create'),
   url(r'^tipo_contato/detalha(?P<pk>\d+)$', TipoContatoUpdateView.as_view(), name='tipo_contato_detail'),
   url(r'^tipo_contato/edita/(?P<pk>\d+)$', TipoContatoDetailView.as_view(), name='tipo_contato_update'),
   url(r'^tipo_contato/exclui/(?P<pk>\d+)$', TipoContatoDeleteView.as_view(), name='tipo_contato_delete'),
   ###  reposicao
   url(r'^reposicao/lista/$', ReposicaoListView.as_view(), name='reposicao_list'),
   url(r'^reposicao/novo/$', ReposicaoCreateView.as_view(), name='reposicao_create'),
   url(r'^reposicao/detalha(?P<pk>\d+)$', ReposicaoDeleteView.as_view(), name='reposicao_detail'),
   url(r'^reposicao/edita/(?P<pk>\d+)$', ReposicaoDetailView.as_view(), name='reposicao_update'),
   url(r'^reposicao/exclui/(?P<pk>\d+)$', ReposicaoUpdateView.as_view(), name='reposicao_delete'),
]

dindri/vendas/models.py
from django.db import models
from django.utils import timezone

from producao.models import Produto
from relacionamento.models import Cliente
from utils.models import Seguranca

# Create your models here.

VENDA_A_VAREJO = 1
VENDA_A_ATACADO = 2

TIPO_VENDA_CHOICES = (
   (VENDA_A_VAREJO, 'Venda no varejo'),
   (VENDA_A_ATACADO, 'Venda no atacado'),
)

ENTREGA_LOCAL = 1
ENTREGA_CONDOMINIO = 2
ENTREGA_EXTERNA = 3

TIPO_ENTREGA_CHOICES = (
   (ENTREGA_LOCAL, 'Entrega local'),
   (ENTREGA_CONDOMINIO, 'Entrega condominio'),
   (ENTREGA_EXTERNA, 'Entrega externa'),
)

PAGTO_A_VISTA = 1
PAGTO_A_PRAZO = 2
PAGTO_PARCELADO = 3

TIPO_PAGAMENTO_CHOICES = (
   (PAGTO_A_VISTA, 'À vista'),
   (PAGTO_A_PRAZO, 'A prazo'),
   (PAGTO_PARCELADO, 'Parcelado'),
)

PAGTO_EM_DINHEIRO = 1
PAGTO_EM_CHEQUE = 2
PAGTO_EM_CARTAO_CREDITO = 3
PAGTO_EM_CARTAO_DEBITO = 4

TIPO_FORMA_PAGAMENTO_CHOICES = (
   (PAGTO_EM_DINHEIRO, 'Em dinheiro'),
   (PAGTO_EM_CHEQUE, 'Em cheque'),
   (PAGTO_EM_CARTAO_DEBITO, 'Cartão débito'),
   (PAGTO_EM_CARTAO_CREDITO, 'Cartão crédito'),
)


class TipoContato(Seguranca):
   nome = models.CharField(max_length=150)
   descricao = models.TextField(max_length=500)

   def __str__(self):
      return self.nome


class Venda(Seguranca):
   data_venda = models.DateTimeField(default=timezone.now)
   tipo_venda = models.IntegerField(choices=TIPO_VENDA_CHOICES, default=1)
   cliente = models.ForeignKey(
      Cliente,
      on_delete=models.PROTECT,
      limit_choices_to={'esta_ativo': True},
   )
   valor_itens_total = models.DecimalField(max_digits=7, decimal_places=2, default=0)
   valor_itens_desconto = models.DecimalField(max_digits=7, decimal_places=2, default=0)
   valor_venda_subtotal = models.DecimalField(max_digits=7, decimal_places=2, default=0)
   valor_venda_desconto = models.DecimalField(max_digits=7, decimal_places=2, default=0)
   valor_venda_total = models.DecimalField(max_digits=7, decimal_places=2, default=0)
   tipo_pagamento = models.IntegerField(choices=TIPO_PAGAMENTO_CHOICES, default=1)
   tipo_forma_pagamento = models.IntegerField(choices=TIPO_FORMA_PAGAMENTO_CHOICES, default=1)
   troco_para = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
   levar_troco = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
   tipo_entrega = models.IntegerField(choices=TIPO_ENTREGA_CHOICES, default=1)
   data_entrega = models.DateTimeField(auto_now_add=True, editable=True)
   esta_entregue = models.BooleanField(default=False)
   esta_pago = models.BooleanField(default=False)
   houve_devolucao = models.BooleanField(default=False)
   necessita_isopor = models.BooleanField(default=False)
   esta_concluida = models.BooleanField(default=False)
   motivo_desconto = models.TextField(max_length=300, null=True, blank=True)

   def is_venda_no_varejo(self):
      return self.tipo_venda == 1

   def is_venda_no_atacado(self):
      return self.tipo_venda == 1

      # def save(self):
      # sub_itens_total = 0
      # sub_itens_descontos = 0
      # sub_vendas_total = 0
      # itens = Venda_Produto.objects.filter(pk = self.pk)
      # for item in itens:
      # sub_itens_subtotal = sub_itens_subtotal + itens.subtotal
      # sub_itens_desconto = sub_itens_desconto + itens.desconto_total
      # self.valor_itens_subtotal = sub_itens_subtotal
      # self.valor_itens_desconto = sub_itens_desconto
      # self.valor_venda_subtotal = (sub_itens_subtotal - sub_itens_desconto) 

   def __str__(self):
      return "%s - %s" % (self.data_venda.strftime("%Y-%m-%d %H:%M:%S"), self.cliente.nome_preferencial)


class VendaProduto(models.Model):
   venda = models.ForeignKey(
      Venda,
      on_delete=models.CASCADE,
      limit_choices_to={'esta_concluida': False},
   )
   produto = models.ForeignKey(
      Produto,
      on_delete=models.PROTECT,
      limit_choices_to={'esta_ativo': True},
   )
   quantidade = models.IntegerField(default=0)

   def get_valor_custo(self):
      return self.produto.valor_custo_produto or 0.0

   valor_custo = property(get_valor_custo)

   def get_valor_minimo(self):
      preco = 0.0
      if self.produto.is_venda_no_varejo():
         preco = self.produto.preco_varejo_minimo
      if self.produto.is_venda_no_atacado():
         preco = self.produto.preco_atacado_minimo
      return preco

   valor_minimo = property(get_valor_minimo)

   def get_valor_unitario(self):
      preco = 0.0
      if self.venda.is_venda_no_varejo():
         preco = self.produto.preco_varejo_sugerido
      if self.venda.is_venda_no_atacado():
         preco = self.produto.preco_atacado_sugerido
      return preco

   valor_unitario = property(get_valor_unitario)

   valor_desconto_unitario = models.DecimalField(max_digits=5, decimal_places=2, default=0)

   def get_valor_subtotal(self):
      return (self.valor_unitario * self.quantidade)

   valor_subtotal = property(get_valor_subtotal)

   def get_valor_desconto_total(self):
      return (self.valor_desconto_unitario * self.quantidade)

   valor_desconto_total = property(get_valor_desconto_total)

   def get_valor_total(self):
      return (self.valor_subtotal - self.valor_desconto_total)

   valor_total = property(get_valor_total)

   def __str__(self):
      return "%s - %i - %f" % (self.produto.nome, self.quantidade, self.valor_total)


class Reposicao(Seguranca):
   data_reposicao = models.DateTimeField(default=timezone.now)
   qtde_reposta = models.IntegerField(default=0)
   custo_reposicao = models.DecimalField(max_digits=10, decimal_places=6, default=0)
   esta_concluida = models.BooleanField(default=False)

   def __str__(self):
      return self.data_reposicao.strftime("%Y-%m-%d %H:%M:%S")


class ReposicaoProduto(models.Model):
   reposicao = models.ForeignKey(
      Reposicao,
      on_delete=models.CASCADE,
      limit_choices_to={'esta_concluida': False},
   )
   produto = models.ForeignKey(
      Produto,
      on_delete=models.PROTECT,
      limit_choices_to={'esta_ativo': True},
   )
   quantidade = models.IntegerField(default=0)
   valor_custo_unitario = models.DecimalField(max_digits=9, decimal_places=6, default=0)

   def get_valor_custo_total(self):
      return (self.quantidade * self.valor_custo_unitario)

   valor_custo_total = property(get_valor_custo_total)

   def __str__(self):
      return "%s - %i - %f" % (self.produto.nome, self.quantidade, self.valor_custo_total)

dindri/vendas/views.py
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from vendas.models import TipoContato, Venda, Reposicao
from vendas.forms import VendaForm, VendaProdutoFormSet, \
   ReposicaoForm, ReposicaoProdutoFormSet, \
   TipoContatoForm


# Create your views here.

### Ambiente de Vendas

class VendasHomeView(TemplateView):
   template_name = 'vendas_home.html'


### venda
class VendaListView(ListView):
   model = Venda
   form_class = VendaForm
   template_name = 'venda_list.html'


class VendaDetailView(DetailView):
   model = Venda
   form_class = VendaForm
   template_name = 'venda_detail.html'


class VendaCreateView(CreateView):
   model = Venda
   form_class = VendaForm
   template_name = 'venda_create.html'
   success_url = 'venda_list'

   def get(self, request, *args, **kwargs):
      """
      Handles GET requests and instantiates blank versions of the form
      and its inline formsets.
      """
      self.object = None
      form_class = self.get_form_class()
      form = self.get_form(form_class)
      venda_produto_form = VendaProdutoFormSet()
      return self.render_to_response(
         self.get_context_data(
            form=form,
            venda_produto_form=venda_produto_form,
         )
      )

   def post(self, request, *args, **kwargs):
      """
      Handles POST requests, instantiating a form instance and its inline
      formsets with the passed POST variables and then checking them for
      validity.
      """
      self.object = None
      form_class = self.get_form_class()
      form = self.get_form(form_class)
      venda_produto_form = VendaProdutoFormSet(self.request.POST)
      if (form.is_valid() and venda_produto_form.is_valid()):
         return self.form_valid(form, venda_produto_form)
      else:
         return self.form_invalid(form, venda_produto_form)

   def form_valid(self, form, venda_produto_form):
      """
      Called if all forms are valid. Creates a Recipe instance along with
      associated Ingredients and Instructions and then redirects to a
      success page.
      """
      self.object = form.save()
      venda_produto_form.instance = self.object
      venda_produto_form.save()
      return HttpResponseRedirect(self.get_success_url())

   def form_invalid(self, form, venda_produto_form):
      """
      Called if a form is invalid. Re-renders the context data with the
      data-filled forms and errors.
      """
      return self.render_to_response(
         self.get_context_data(
            form=form,
            venda_produto_form=venda_produto_form,
         )
      )


class VendaUpdateView(UpdateView):
   model = Venda
   form_class = VendaForm
   template_name = 'venda_update.html'
   success_url = 'venda_list'
   success_url = 'venda_list'

   def get(self, request, *args, **kwargs):
      """
      Handles GET requests and instantiates blank versions of the form
      and its inline formsets.
      """
      self.object = None
      form_class = self.get_form_class()
      form = self.get_form(form_class)
      venda_produto_form = VendaProdutoFormSet()
      return self.render_to_response(
         self.get_context_data(
            form=form,
            venda_produto_form=venda_produto_form,
         )
      )

   def post(self, request, *args, **kwargs):
      """
      Handles POST requests, instantiating a form instance and its inline
      formsets with the passed POST variables and then checking them for
      validity.
      """
      self.object = None
      form_class = self.get_form_class()
      form = self.get_form(form_class)
      venda_produto_form = VendaProdutoFormSet(self.request.POST)
      if (form.is_valid() and venda_produto_form.is_valid()):
         return self.form_valid(form, venda_produto_form)
      else:
         return self.form_invalid(form, venda_produto_form)

   def form_valid(self, form, venda_produto_form):
      """
      Called if all forms are valid. Creates a Recipe instance along with
      associated Ingredients and Instructions and then redirects to a
      success page.
      """
      self.object = form.save()
      venda_produto_form.instance = self.object
      venda_produto_form.save()
      return HttpResponseRedirect(self.get_success_url())

   def form_invalid(self, form, venda_produto_form):
      """
      Called if a form is invalid. Re-renders the context data with the
      data-filled forms and errors.
      """
      return self.render_to_response(
         self.get_context_data(
            form=form,
            venda_produto_form=venda_produto_form,
         )
      )


class VendaDeleteView(DeleteView):
   model = Venda
   form_class = VendaForm
   template_name = 'venda_delete_confirm.html'
   success_url = 'venda_list'


### Tipo_Contato
class TipoContatoListView(ListView):
   model = TipoContato
   template_name = 'tipo_contato_list.html'


class TipoContatoDetailView(DetailView):
   model = TipoContato
   form_class = TipoContatoForm
   template_name = 'tipo_contato_detail.html'


class TipoContatoCreateView(CreateView):
   model = TipoContato
   form_class = TipoContatoForm
   template_name = 'tipo_contato_create.html'
   success_url = 'tipo_contato_list'


class TipoContatoUpdateView(UpdateView):
   model = TipoContato
   form_class = TipoContatoForm
   template_name = 'tipo_contato_create.html'
   success_url = 'tipo_contato_list'


class TipoContatoDeleteView(DeleteView):
   model = TipoContato
   form_class = TipoContatoForm
   template_name = 'tipo_contato_delete_confirm.html'
   success_url = 'tipo_contato_list'


### reposicao
class ReposicaoListView(ListView):
   model = Reposicao
   form_class = ReposicaoForm
   template_name = 'reposicao_list.html'


class ReposicaoDetailView(DetailView):
   model = Reposicao
   form_class = ReposicaoForm
   template_name = 'reposicao_detail.html'


class ReposicaoCreateView(CreateView):
   model = Reposicao
   form_class = ReposicaoForm
   template_name = 'reposicao_create.html'
   success_url = 'reposicao_list'

   def get(self, request, *args, **kwargs):
      """
      Handles GET requests and instantiates blank versions of the form
      and its inline formsets.
      """
      self.object = None
      form_class = self.get_form_class()
      form = self.get_form(form_class)
      reposicao_produto_form = ReposicaoProdutoFormSet()
      return self.render_to_response(
         self.get_context_data(
            form=form,
            reposicao_produto_form=reposicao_produto_form,
         )
      )

   def post(self, request, *args, **kwargs):
      """
      Handles POST requests, instantiating a form instance and its inline
      formsets with the passed POST variables and then checking them for
      validity.
      """
      self.object = None
      form_class = self.get_form_class()
      form = self.get_form(form_class)
      reposicao_produto_form = ReposicaoProdutoFormSet(self.request.POST)
      if (form.is_valid() and reposicao_produto_form.is_valid()):
         return self.form_valid(form, reposicao_produto_form)
      else:
         return self.form_invalid(form, reposicao_produto_form)

   def form_valid(self, form, reposicao_produto_form):
      """
      Called if all forms are valid. Creates a Recipe instance along with
      associated Ingredients and Instructions and then redirects to a
      success page.
      """
      self.object = form.save()
      reposicao_produto_form.instance = self.object
      reposicao_produto_form.save()
      return HttpResponseRedirect(self.get_success_url())

   def form_invalid(self, form, reposicao_produto_form):
      """
      Called if a form is invalid. Re-renders the context data with the
      data-filled forms and errors.
      """
      return self.render_to_response(
         self.get_context_data(
            form=form,
            reposicao_produto_form=reposicao_produto_form,
         )
      )


class ReposicaoUpdateView(UpdateView):
   model = Reposicao
   form_class = ReposicaoForm
   template_name = 'reposicao_update.html'
   success_url = 'reposicao_list'


class ReposicaoDeleteView(DeleteView):
   model = Reposicao
   form_class = ReposicaoForm
   template_name = 'reposicao_delete_confirm.html'
   success_url = 'reposicao_list'

dindri/vendas/templates/menu_vendas.html
<div class='list-group'>
    <a class='list-group-item' href="{% url 'vendas_home' %}">Home</a>
    <a class='list-group-item' href="{% url 'venda_list' %}">Vendas</a>
    <a class='list-group-item' href="{% url 'reposicao_list' %}">Reposicões</a>
    <a class='list-group-item' href="{% url 'tipo_contato_list' %}">Tipos de contatos</a>
    </ul>

dindri/vendas/templates/reposicao_delete_confirm.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block menu %} {% include 'home_menu.html' %} {% endblock %}
{% block titulo %} {% include 'vendas.html' %} {% endblock %}
{% block main %}
<h1>Confirmação da exclusão da reposição</h1>
<form method='POST'>
    {% csrf_token %}
    <p>Você tem certeza que deseja excluir a reposição {{object}}</p>
    <button type='submit' class='btn-danger'>Tenho certeza</button>
</form>
{% endblock %}

dindri/vendas/templates/reposicao_list.html
{% extends 'base.html' %}
{% block menu %}{% include 'home_menu.html' %}{% endblock %}
{% block titulo %}{% include 'vendas.html' %}{% endblock %}
{% block main %}
<h1>Lista Reposições</h1>
{% if object_list %}
<div class="panel-group">
    <div class="panel panel-default">
        {% for reposicao in object_list %}
        <div class="panel-heading">
            <h4 class="panel-title panel-success">
                <a data-toggle="collapse" href="#reposicao{{reposicao.id}}"><span
                        class="glyphicon glyphicon-plus"></span></a>
                <a href="">{{ reposicao }}</a>
            </h4>
        </div>
        <div id="reposicao{{reposicao.id}}" class="panel-collapse collapse">
            {% for detail in reposicao.reposicaoproduto_set.all %}
            <div class="panel-heading panel-info">{{detail}}</div>
            {% empty %}
            <div class="panel-heading panel-danger">Não há itens nesta reposição.</div>
            {% endfor %}
        </div>
        {% endfor %}
    </div>
</div>
{% else %}
<div class="alert alert-info">Não há reposição cadastrada.</div>
{% endif %}
<div class='panel-heading panel-success'>
    <a class='btn btn-success btn-lg' href="{% url 'reposicao_create' %}">Nova reposição</a>
</div>
{% endblock %}

dindri/vendas/templates/tipo_contato_delete_confirm.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block menu %} {% include 'home_menu.html' %} {% endblock %}
{% block titulo %} {% include 'vendas.html' %} {% endblock %}
{% block main %}
<h1>Confirmação da exclusão do tipo de contato</h1>
<form method='POST'>
    {% csrf_token %}
    <p>Você tem certeza que deseja excluir o tipo de contato {{object}}</p>
    <button type='submit' class='btn-danger'>Tenho certeza</button>
</form>
{% endblock %}

dindri/vendas/templates/tipo_contato_detail.html
{% extends 'base.html' %}
{% block menu %} {% include 'home_menu.html' %} {% endblock %}
{% block titulo %} {% include 'vendas.html' %} {% endblock %}
{% block main %}
<h1>Editar dados do tipo de contato</h1>
<p>{{object.nome}}</p>
<p>{{object.descricao}}</p>
<p><a class="btn btn-success" href="{% url 'tipo_contato_update' object.id %}">Editar</a></p>
<p><a class="btn btn-danger" href="{% url 'tipo_contato_delete' object.id %}">Excluir</a></p>
<p><a class='btn btn-info" href="{% url ' tipo_contato_list' %}">Voltar</a></p>
{% endblock %}

dindri/vendas/templates/tipo_contato_list.html
{% extends 'base.html' %}
{% block menu %} {% include 'home_menu.html' %} {% endblock %}
{% block titulo %} {% include 'vendas.html' %} {% endblock %}
{% block main %}
<h1>Lista de tipos de contatos</h1>
{% if object_list %}
<div class='list-group'>
    {% for tipo_contato in object_list %}
    <a class='list-group-item' href="{% url 'tipo_contato_detail' tipo_contato.id %}">{{tipo_contato}}</a>
    {% endfor %}
</div>
{% else %}
<div class='alert alert-info'>Não há tipo de contato cadastrado.</div>
{% endif %}
<div class="panel-heading panel-success">
    <a class='btn btn-success btn-lg' href="{% url 'tipo_contato_create' %}">Novo tipo de contato</a>
</div>
{% endblock %}

dindri/vendas/templates/tipo_contato_update.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block menu %} {% include 'home_menu.html' %} {% endblock %}
{% block titulo %} {% include 'vendas.html' %} {% endblock %}
{% block main %}
<h1>Editar dados do tipo de contato</h1>
<form method='POST'>
    {% csrf_token %}
    {{form|bootstrap}}
    <button type='submit' class='btn btn-success'>Salvar</button>
</form>
{% endblock %}

dindri/vendas/templates/venda_create.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block menu %} {% include 'home_menu.html' %} {% endblock %}
{% block titulo %} {% include 'vendas.html' %} {% endblock %}
{% block javascript %}
<script type="text/javascript">
        $(function() {
            $(".inline.{{ venda_produto_form.prefix }}").formset({
                prefix: "{{ venda_produto_form.prefix }}",
            })
        })

</script>
{% endblock %}
{% block main %}
<div>
    <h1>Incluir venda</h1>
    <form method='POST'>
        {% csrf_token %}
        <div>
            {{ form.as_p }}
        </div>
        <fieldset>
            <legend>Produtos</legend>
            {{ venda_produto_form.management_form }}
            {{ venda_produto_form.non_form_errors }}
            {% for item in venda_produto_form %}
            {{ item.id }}
            <div class="inline {{ venda_produto_form.prefix }}">
                {{ item.produto.errors }}
                {{ item.produto.label_tag }}
                {{ item.produto }}
                {{ item.quantidade.errors }}
                {{ item.quantidade.label_tag }}
                {{ item.quantidade }}
                {{ item.valor_custo.errors }}
                {{ item.valor_custo.label_tag }}
                {{ item.valor_custo }}
                {{ item.valor_minimo.errors }}
                {{ item.valor_minimo.label_tag }}
                {{ item.valor_minimo }}
                {{ item.valor_unitario.errors }}
                {{ item.valor_unitario.label_tag }}
                {{ item.valor_unitario }}
                {{ item.valor_desconto_unitario.errors }}
                {{ item.valor_desconto_unitario.label_tag }}
                {{ item.valor_desconto_unitario }}
                {{ item.valor_subtotal.errors }}
                {{ item.valor_subtotal.label_tag }}
                {{ item.valor_subtotal }}
                {{ item.valor_desconto_total.errors }}
                {{ item.valor_desconto_total.label_tag }}
                {{ item.valor_desconto_total }}
                {{ item.valor_total.errors }}
                {{ item.valor_total.label_tag }}
                {{ item.valor_total }}
            </div>
            {% endfor %}
        </fieldset>
        <input type="submit" value="Salvar" class="class='btn btn-success"/>
    </form>
</div>
{% endblock %}

dindri/vendas/templates/venda_delete_confirm.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block menu %} {% include 'home_menu.html' %} {% endblock %}
{% block titulo %} {% include 'vendas.html' %} {% endblock %}
{% block main %}
<h1>Confirmação da exclusão da venda</h1>
<form method='POST'>
    {% csrf_token %}
    <p>Você tem certeza que deseja excluir a venda {{object}}</p>
    <button type='submit' class='btn-danger'>Tenho certeza</button>
</form>
{% endblock %}

dindri/vendas/templates/venda_detail.html
{% extends 'base.html' %}
{% block menu %} {% include 'home_menu.html' %} {% endblock %}
{% block titulo %} {% include 'vendas.html' %} {% endblock %}
{% block main %}
<h1>Editar dados da reposição</h1>
<div class="panel">
    <div class="panel-heading panel-success">
        {{object}}
    </div>
    <div class="panel-group">
        {% for item in object.vendaproduto_set.all %}
        <div class="panel-heading panel-info">{{item}}</div>
        {% endfor %}
    </div>
</div>
<div class="btn-group">
    <a class="btn btn-success" href="{% url 'venda_update' object.id %}">Editar</a>
    <a class="btn btn-danger" href="{% url 'venda_delete' object.id %}">Excluir</a>
    <a class="btn btn-info" href="{% url 'venda_list' %}">Voltar</a>
</div>
{% endblock %}

dindri/vendas/templates/venda_list.html
{% extends 'base.html' %}
{% block menu %}{% include 'home_menu.html' %}{% endblock %}
{% block titulo %}{% include 'vendas.html' %}{% endblock %}
{% block main %}
<h1>Lista de Vendas</h1>
{% if object_list %}
<div class="panel-group">
    <div class="panel panel-default">
        {% for venda in object_list %}
        <div class="panel-heading">
            <h4 class="panel-title panel-success">
                <a data-toggle="collapse" href="#venda{{venda.id}}"><span class="glyphicon glyphicon-plus"></span></a>
                <h1 href="{% url 'venda_detail' venda.id %}">{{ venda }}</h1>
            </h4>
        </div>
        <div id="venda{{venda.id}}" class="panel-collapse collapse">
            {% for detail in venda.venda_produto_set.all %}
            <div class="panel-heading panel-info">{{detail}}</div>
            {% empty %}
            <div class="panel-heading panel-danger">Não há itens nesta venda.</div>
            {% endfor %}
        </div>
        {% endfor %}
    </div>
</div>
{% else %}
<div class="alert alert-info">Não há venda cadastrada.</div>
{% endif %}
<div class="panel-heading panel-success">
    <a class="btn btn-success btn-lg" href="{% url 'venda_create' %}">Nova venda</a>
</div>
{% endblock %}

dindri/vendas/templates/vendas.html
Vendas

dindri/vendas/templates/vendas_home.html
{% extends 'base.html' %}
{% block menu %}{% include 'home_menu.html' %}{% endblock %}
{% block titulo %} {% include 'vendas.html' %} {% endblock %}
{% block main %}{% include 'menu_vendas.html' %}{% endblock %}