dindri/dindri/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from home import views as home_views

urlpatterns = [
   url(r'^$', home_views.home, name='home'),
   url(r'^relacionamento/', include('relacionamento.urls')),
   url(r'^vendas/', include('vendas.urls')),
   url(r'^compras/', include('compras.urls')),
   url(r'^estoque/', include('estoque.urls')),
   url(r'^producao/', include('producao.urls')),
   url(r'^receitas/', include('receitas.urls')),
   url(r'^admin/', admin.site.urls),
]

dindri/home/urls.py
from django.conf.urls import url
from django.contrib import admin
from home import views as home_views

urlpatterns = [
   url(r'^$', home_views.home, name='home_page'),
]

dindri/producao/urls.py
from django.conf.urls import url
from producao.views import ProducaoHomeView
from producao.views import InsumoListView, InsumoDetailView, InsumoCreateView, InsumoUpdateView, InsumoDeleteView
from producao.views import LoteBaseListView, LoteBaseDetailView, LoteBaseCreateView, LoteBaseUpdateView, \
   LoteBaseDeleteView
from producao.views import LoteSaborListView, LoteSaborDetailView, LoteSaborCreateView, LoteSaborUpdateView, \
   LoteSaborDeleteView
from producao.views import LoteProdutoListView, LoteProdutoDetailView, LoteProdutoCreateView, LoteProdutoUpdateView, \
   LoteProdutoDeleteView
from producao.views import TipoBaseListView, TipoBaseDetailView, TipoBaseCreateView, TipoBaseUpdateView, \
   TipoBaseDeleteView, TipoBaseActiveView
from producao.views import TipoSaborListView, TipoSaborDetailView, TipoSaborCreateView, TipoSaborUpdateView, \
   TipoSaborDeleteView, TipoSaborActiveView
from producao.views import TipoProdutoListView, TipoProdutoDetailView, TipoProdutoCreateView, TipoProdutoUpdateView, \
   TipoProdutoDeleteView, TipoProdutoActiveView
from producao.views import BaseListView, BaseDetailView, BaseCreateView, BaseUpdateView, BaseDeleteView
from producao.views import SaborListView, SaborDetailView, SaborCreateView, SaborUpdateView, SaborDeleteView
from producao.views import ProdutoListView, ProdutoDetailView, ProdutoCreateView, ProdutoUpdateView, ProdutoDeleteView

urlpatterns = [
   ###  home
   url(r'^$', ProducaoHomeView.as_view(), name='producao_home'),
   ###  insumo 
   url(r'^insumo/lista/$', InsumoListView.as_view(), name='insumo_list'),
   url(r'^insumo/novo/$', InsumoCreateView.as_view(), name='insumo_create'),
   url(r'^insumo/detalha(?P<pk>\d+)$', InsumoDetailView.as_view(), name='insumo_detail'),
   url(r'^insumo/edita/(?P<pk>\d+)$', InsumoUpdateView.as_view(), name='insumo_update'),
   url(r'^insumo/exclui/(?P<pk>\d+)$', InsumoDeleteView.as_view(), name='insumo_delete'),
   ###  lote_base
   url(r'^lote_base/lista/$', LoteBaseListView.as_view(), name='lote_base_list'),
   url(r'^lote_base/novo/$', LoteBaseCreateView.as_view(), name='lote_base_create'),
   url(r'^lote_base/detalha(?P<pk>\d+)$', LoteBaseDetailView.as_view(), name='lote_base_detail'),
   url(r'^lote_base/edita/(?P<pk>\d+)$', LoteBaseUpdateView.as_view(), name='lote_base_update'),
   url(r'^lote_base/exclui/(?P<pk>\d+)$', LoteBaseDeleteView.as_view(), name='lote_base_delete'),
   ###  lote_sabor
   url(r'^lote_sabor/lista/$', LoteSaborListView.as_view(), name='lote_sabor_list'),
   url(r'^lote_sabor/novo/$', LoteSaborCreateView.as_view(), name='lote_sabor_create'),
   url(r'^lote_sabor/detalha(?P<pk>\d+)$', LoteSaborDetailView.as_view(), name='lote_sabor_detail'),
   url(r'^lote_sabor/edita/(?P<pk>\d+)$', LoteSaborUpdateView.as_view(), name='lote_sabor_update'),
   url(r'^lote_sabor/exclui/(?P<pk>\d+)$', LoteSaborDeleteView.as_view(), name='lote_sabor_delete'),
   ###  lote_produto
   url(r'^lote_produto/lista/$', LoteProdutoListView.as_view(), name='lote_produto_list'),
   url(r'^lote_produto/novo/$', LoteProdutoCreateView.as_view(), name='lote_produto_create'),
   url(r'^lote_produto/detalha(?P<pk>\d+)$', LoteProdutoDetailView.as_view(), name='lote_produto_detail'),
   url(r'^lote_produto/edita/(?P<pk>\d+)$', LoteProdutoUpdateView.as_view(), name='lote_produto_update'),
   url(r'^lote_produto/exclui/(?P<pk>\d+)$', LoteProdutoDeleteView.as_view(), name='lote_produto_delete'),
   ###  tipo_base
   url(r'^tipo_base/lista/$', TipoBaseListView.as_view(), name='tipo_base_list'),
   url(r'^tipo_base/novo/$', TipoBaseCreateView.as_view(), name='tipo_base_create'),
   url(r'^tipo_base/detalha/(?P<pk>\d+)$', TipoBaseDetailView.as_view(), name='tipo_base_detail'),
   url(r'^tipo_base/edita/(?P<pk>\d+)$', TipoBaseUpdateView.as_view(), name='tipo_base_update'),
   url(r'^tipo_base/exclui/(?P<pk>\d+)$', TipoBaseDeleteView.as_view(), name='tipo_base_delete'),
   url(r'^tipo_base/ativa/(?P<pk>\d+)$', TipoBaseActiveView.as_view(), name='tipo_base_active'),
   ###  tipo_sabor
   url(r'^tipo_sabor/lista/$', TipoSaborListView.as_view(), name='tipo_sabor_list'),
   url(r'^tipo_sabor/novo/$', TipoSaborCreateView.as_view(), name='tipo_sabor_create'),
   url(r'^tipo_sabor/detalha/(?P<pk>\d+)$', TipoSaborDetailView.as_view(), name='tipo_sabor_detail'),
   url(r'^tipo_sabor/edita/(?P<pk>\d+)$', TipoSaborUpdateView.as_view(), name='tipo_sabor_update'),
   url(r'^tipo_sabor/exclui/(?P<pk>\d+)$', TipoSaborDeleteView.as_view(), name='tipo_sabor_delete'),
   url(r'^tipo_sabor/ativa/(?P<pk>\d+)$', TipoSaborActiveView.as_view(), name='tipo_sabor_active'),
   ###  tipo_produto
   url(r'^tipo_produto/lista/$', TipoProdutoListView.as_view(), name='tipo_produto_list'),
   url(r'^tipo_produto/novo/$', TipoProdutoCreateView.as_view(), name='tipo_produto_create'),
   url(r'^tipo_produto/detalha/(?P<pk>\d+)$', TipoProdutoDetailView.as_view(), name='tipo_produto_detail'),
   url(r'^tipo_produto/edita/(?P<pk>\d+)$', TipoProdutoUpdateView.as_view(), name='tipo_produto_update'),
   url(r'^tipo_produto/exclui/(?P<pk>\d+)$', TipoProdutoDeleteView.as_view(), name='tipo_produto_delete'),
   url(r'^tipo_produto/ativa/(?P<pk>\d+)$', TipoProdutoActiveView.as_view(), name='tipo_produto_active'),
   ###  base
   url(r'^base/lista/$', BaseListView.as_view(), name='base_list'),
   url(r'^base/novo/$', BaseCreateView.as_view(), name='base_create'),
   url(r'^base/detalha(?P<pk>\d+)$', BaseDetailView.as_view(), name='base_detail'),
   url(r'^base/edita/(?P<pk>\d+)$', BaseUpdateView.as_view(), name='base_update'),
   url(r'^base/exclui/(?P<pk>\d+)$', BaseDeleteView.as_view(), name='base_delete'),
   ###  sabor
   url(r'^sabor/lista/$', SaborListView.as_view(), name='sabor_list'),
   url(r'^sabor/novo/$', SaborCreateView.as_view(), name='sabor_create'),
   url(r'^sabor/detalha/(?P<pk>\d+)$', SaborDetailView.as_view(), name='sabor_detail'),
   url(r'^sabor/edita/(?P<pk>\d+)$', SaborUpdateView.as_view(), name='sabor_update'),
   url(r'^sabor/exclui/(?P<pk>\d+)$', SaborDeleteView.as_view(), name='sabor_delete'),
   ###  produto
   url(r'^produto/lista/$', ProdutoListView.as_view(), name='produto_list'),
   url(r'^produto/novo/$', ProdutoCreateView.as_view(), name='produto_create'),
   url(r'^produto/detalha(?P<pk>\d+)$', ProdutoDetailView.as_view(), name='produto_detail'),
   url(r'^produto/edita/(?P<pk>\d+)$', ProdutoUpdateView.as_view(), name='produto_update'),
   url(r'^produto/exclui/(?P<pk>\d+)$', ProdutoDeleteView.as_view(), name='produto_delete'),
]

dindri/producao/models.py
from django.utils import timezone
from django.db import models
from utils.models import Seguranca, Restricao
from estoque.models import Item


# Create your models here.

class Insumo(Seguranca, Restricao):
   produto = models.ForeignKey(
      Item,
      on_delete=models.PROTECT,
      limit_choices_to={'esta_ativo': True},
   )
   volume = models.PositiveIntegerField()
   valor_custo_medida = models.DecimalField(
      max_digits=12,
      decimal_places=6,
      default=0.0,
   )
   valor_custo_medio_medida = models.DecimalField(
      max_digits=12,
      decimal_places=6,
      default=0.0,
   )

   def get_absolute_url(self):
      return 'insumo_list'

   def save(self, *args, **kwargs):
      self.restringir()
      return super(Insumo, self).save(*args, **kwargs)

   def delete(self, *args, **kwargs):
      self.excluir()
      super(Insumo, self).save(*args, **kwargs)
      return

   def __str__(self):
      return "%i - %s" % (self.id, self.nome)

class LoteCusto(Seguranca, Restricao):
   data_producao = models.DateTimeField(
      auto_now_add=True,
   )
   data_producao_finalizada = models.DateTimeField(
      null=True,
      blank=True,
   )
   data_ultimo_consumo = models.DateTimeField(
      null=True,
      blank=True,
   )
   data_ultimo_descarte = models.DateTimeField(
      null=True,
      blank=True,
   )
   esta_finalizado = models.BooleanField(
      default=False,
   )
   volume_produzido = models.PositiveIntegerField(
      default=0,
   )
   volume_consumido = models.PositiveIntegerField(
      default=0,
   )
   volume_descartada = models.PositiveIntegerField(
      default=0,
   )

   def get_volume_estoque(self):
      return (self.volume_produzido - (self.volume_consumido + self.volume_descartado))

   volume_estoque = property(get_volume_estoque)

   valor_custo_volume_total = models.DecimalField(
      max_digits=12,
      decimal_places=6,
      default=0.0,
   )

   def get_valor_custo_volume_ml(self):
      return (self.valor_custo_volume_total / self.volume_produzido)

   valor_custo_volume_ml = property(get_valor_custo_volume_ml)

   quantidade_dindin_produzido = models.PositiveIntegerField(
      default=0,
   )

   def get_valor_custo_volume_por_dindin(self):
      return (self.valor_custo_volume_total / self.quantidade_dindin_produzido)

   valor_custo_volume_por_dindin = property(get_valor_custo_volume_por_dindin)

   def get_rendimento_volume_por_dindin(self):
      return (self.volume_produzido / self.quantidade_dindin_produzido)

   rendimento_volume_por_dindin = property(get_rendimento_volume_por_dindin)

   class Meta:
      abstract = True

class BaseCusto(Seguranca, Restricao):
   nome = models.CharField(max_length=150)
   descricao = models.TextField(max_length=512)
   data_producao = models.DateTimeField(
      auto_now_add=True,
      editable=True,
   )
   data_producao_finalizada = models.DateTimeField(
      auto_now_add=True,
      editable=True,
   )
   esta_finalizada = models.BooleanField(
      default=False,
   )
   volume_produzido = models.PositiveIntegerField()
   volume_consumido = models.PositiveIntegerField(
      default=0,
   )
   volume_descartado = models.PositiveIntegerField(
      default=0,
   )

   def get_volume_estoque(self):
      return (self.volume_produzido - (self.volume_consumido + self.volume_descartado))

   volume_estoque = property(get_volume_estoque)

   valor_custo_operacional = models.DecimalField(
      max_digits=9,
      decimal_places=6,
      default=0.0
   )
   valor_custo_infraestrutura = models.DecimalField(
      max_digits=9,
      decimal_places=6,
      default=0.0,
   )
   valor_custo_insumo = models.DecimalField(
      max_digits=9,
      decimal_places=6,
      default=0.0,
   )

   def get_valor_custo_volume_total(self):
      return (self.valor_custo_operacional + self.valor_custo_infraestutura + self.valor_custo_insumo)

   valor_custo_volume_total = property(get_valor_custo_volume_total)

   def get_valor_custo_volume_ml(self):
      return (self.valor_custo_volume_total / self.volume_produzido)

   valor_custo_volume_ml = property(get_valor_custo_volume_ml)

   quantidade_dindin_produzido = models.PositiveIntegerField(
      default=0,
   )

   def get_valor_custo_volume_por_dindin(self):
      return (self.valor_custo_volume_total / self.quantidade_dindin_produzido)

   valor_custo_volume_por_dindin = property(get_valor_custo_volume_por_dindin)

   def get_rendimento_volume_por_dindin(self):
      return (self.volume_produzido / self.quantidade_dindin_produzido)

   rendimento_volume_por_dindin = property(get_rendimento_volume_por_dindin)

   class Meta:
      abstract = True

class LoteBase(LoteCusto):
   def __str__(self):
      return "%i - %s" % (self.id, self.data_producao)

class LoteSabor(LoteCusto):
   def __str__(self):
      return "%i - %s" % (self.id, self.data_producao)

class LoteProduto(LoteCusto):
   def __str__(self):
      return "%i - %s" % (self.id, self.data_producao)

class TipoBase(Seguranca, Restricao):
   nome = models.CharField(
      max_length=150,
   )
   descricao = models.TextField(
      max_length=512,
   )

   def get_absolute_url(self):
      return 'tipo_sabor_list'

   def save(self, *args, **kwargs):
      self.restringir()
      return super(TipoBase, self).save(*args, **kwargs)

   def delete(self, *args, **kwargs):
      self.excluir()
      super(TipoBase, self).save(*args, **kwargs)
      return

   def __str__(self):
      return self.nome

class Base(BaseCusto):
   lote = models.ForeignKey(
      LoteBase,
      on_delete=models.PROTECT,
      limit_choices_to={'esta_ativo': True},
   )
   tipo_de_base = models.ForeignKey(
      TipoBase,
      on_delete=models.PROTECT,
      limit_choices_to={'esta_ativo': True},
   )

   def __str__(self):
      return "%s %s - %i ml" % (self.tipo_de_base.nome, str(self.data_base), self.volume_estoque)

class BaseInsumo(models.Model):
   base = models.ForeignKey(
      Base,
      on_delete=models.CASCADE,
   )
   insumo = models.ForeignKey(
      Insumo,
      on_delete=models.PROTECT,
   )
   quantidade = models.PositiveSmallIntegerField()
   valor_custo_unitario = models.DecimalField(
      max_digits=9,
      decimal_places=6,
      default=0.0,
   )

   def get_valor_custo_total(self):
      return (self.quantidade * self.valor_custo_unitario)

   valor_custo_total = property(get_valor_custo_total)

   def __str__(self):
      return "%s - %i - %f" % (self.insumo.nome, self.quantidade, self.valor_custo_total)

class BaseConsumo(models.Model):
   base = models.ForeignKey(
      Base,
      on_delete=models.CASCADE,
   )
   data_consumo = models.DateTimeField(
      auto_now_add=True,
   )
   volume_consumido = models.PositiveSmallIntegerField()

   def __str__(self):
      return "%s - %i" % (str(self.data_consumo), self.volume_consumido)

class BaseDescarte(models.Model):
   base = models.ForeignKey(
      Base,
      on_delete=models.CASCADE,
   )
   data_descarte = models.DateTimeField(
      auto_now_add=True,
   )
   volume_descarte = models.PositiveSmallIntegerField()

   def __str__(self):
      return "%s - %i" % (str(self.data_descarte), self.volume_descarte)

      # class TipoInsumo(Seguranca, Restricao):
      # nome = models.CharField(
      # max_length=150,
      # )
      # descricao = models.TextField(
      # max_length=512,
      # )

      # def __str__(self):
      # return "%i - %s" % (self.id, self.nome)

class TipoSabor(Seguranca, Restricao):
   nome = models.CharField(
      max_length=150,
   )
   descricao = models.TextField(
      max_length=512,
   )

   def get_absolute_url(self):
      return 'tipo_sabor_list'

   def save(self, *args, **kwargs):
      self.restringir()
      return super(TipoSabor, self).save(*args, **kwargs)

   def delete(self, *args, **kwargs):
      self.excluir()
      super(TipoSabor, self).save(*args, **kwargs)
      return

   def __str__(self):
      return "%i - %s" % (self.id, self.nome)

class Sabor(BaseCusto):
   lote = models.ForeignKey(
      LoteSabor,
      on_delete=models.PROTECT,
      limit_choices_to={'esta_ativo': True},
   )
   tipo_sabor = models.ForeignKey(
      TipoSabor,
      on_delete=models.PROTECT,
      limit_choices_to={'esta_ativo': True},
   )

   def get_absolute_url(self):
      return 'sabor_list'

   def delete(self, *args, **kwargs):
      self.excluido_em = timezone.now()
      self.esta_ativo = False
      self.esta_excluido = True
      super(Sabor, self).save(*args, **kwargs)
      return

class SaborBase(models.Model):
   sabor = models.ForeignKey(
      Sabor,
      on_delete=models.CASCADE,
   )
   base = models.ForeignKey(
      Base,
      on_delete=models.CASCADE,
   )
   volume = models.PositiveSmallIntegerField()
   valor_custo_unitario = models.DecimalField(
      max_digits=9,
      decimal_places=6,
   )

   def get_valor_custo_total(self):
      return (self.volume * self.valor_custo_unitario)

   valor_custo_total = property(get_valor_custo_total)

   def __str__(self):
      return "%s - %i - %f" % ((self.base.data_producao), self.volume, self.valor_custo_total)

class SaborInsumo(models.Model):
   sabor = models.ForeignKey(
      Sabor,
      on_delete=models.CASCADE,
   )
   insumo = models.ForeignKey(
      Insumo,
      on_delete=models.CASCADE,
      limit_choices_to={'esta_ativo': True},
   )
   volume = models.PositiveSmallIntegerField()
   valor_custo_unitario = models.DecimalField(
      max_digits=9,
      decimal_places=6,
   )

   def get_valor_custo_total(self):
      return (self.volume * self.valor_custo_unitario)

   valor_custo_total = property(get_valor_custo_total)

   def __str__(self):
      return "%s - %i - %f" % ((self.base.data_producao), self.volume, self.valor_custo_total)

class SaborConsumo(models.Model):
   sabor = models.ForeignKey(
      Sabor,
      on_delete=models.CASCADE,
   )
   data_consumo = models.DateTimeField(
      auto_now_add=True)

dindri/producao/templates/base_detail.html
{% extends 'base.html' %}
{% block menu %} {% include 'home_menu.html' %} {% endblock %}
{% block titulo %} {% include 'producao.html' %} {% endblock %}
{% block main %}
<h1>Detalhes da base</h1>
<p>{{object.nome}}</p>
<p>{{object.descricao}}</p>
<p><a class="btn btn-success" href="{% url 'base_update' object.id %}">Editar</a></p>
<p><a class="btn btn-danger" href="{% url 'base_delete' object.id %}">Excluir</a></p>
<p><a class='btn btn-info" href="{% url ' base_list' %}">Voltar</a></p>
{% endblock %}

dindri/producao/templates/lote_base_delete_confirm.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block menu %} {% include 'home_menu.html' %} {% endblock %}
{% block titulo %} {% include 'producao.html' %} {% endblock %}
{% block main %}
<h1>Confirmação da exclusão do lote de base</h1>
<form method='POST'>
    {% csrf_token %}
    <p>Você tem certeza que deseja excluir o lote de base {{object}}</p>
    <button type='submit' class='btn-danger'>Tenho certeza</button>
</form>
{% endblock %}

dindri/producao/templates/lote_base_list.html
{% extends 'base.html' %}
{% block menu %} {% include 'home_menu.html' %} {% endblock %}
{% block titulo %} {% include 'producao.html' %} {% endblock %}
{% block main %}
<h1>Lista de lotes de bases</h1>
{% for lote_base in object %}
<div class='list-group'>
    <a class='list-group-item' href="{% url 'lote_base_detail' lote_base.id %}">{{lote_base}}</a>
</div>
{% empty %}
<div class="alert alert-info">Não há lote de base cadastrada.</div>
{% endfor %}
<div class="panel-heading panel-success">
    <a class='btn btn-success btn-lg' href="{% url 'lote_base_create' %}">Novo lote de base</a>
</div>
{% endblock %}

dindri/producao/templates/lote_produto_detail.html
{% extends 'base.html' %}
{% block menu %} {% include 'home_menu.html' %} {% endblock %}
{% block titulo %} {% include 'producao.html' %} {% endblock %}
{% block main %}
<h1>Detalhe do lote de produto</h1>
<p>{{object.nome}}</p>
<p>{{object.descricao}}</p>
<p><a class="btn btn-success" href="{% url 'lote_produto_update' object.id %}">Editar</a></p>
<p><a class="btn btn-danger" href="{% url 'lote_produto_delete' object.id %}">Excluir</a></p>
<p><a class='btn btn-info" href="{% url ' lote_produto_list' %}">Voltar</a></p>
{% endblock %}

dindri/producao/templates/lote_sabor_delete_confirm.html
{% extends 'base.html' %}
{% block menu %} {% include 'home_menu.html' %} {% endblock %}
{% block titulo %} {% include 'producao.html' %} {% endblock %}
{% block main %}
<h1>Confirmação da exclusão do lote de sabor</h1>
<form method='POST'>
    {% csrf_token %}
    <p>Você tem certeza que deseja excluir o lote de sabor {{object}}</p>
    <button type='submit' class='btn-danger'>Tenho certeza</button>
</form>
{% endblock %}

dindri/producao/templates/producao.html
Produção

dindri/producao/templates/producao_home.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block javascript %}
<link href="{% static 'css/producao.css' %}" rel="stylesheet">
{% endblock %}
{% block menu %} {% include 'home_menu.html' %} {% endblock %}
{% block titulo %} {% include 'producao.html' %} {% endblock %}
{% block main %} {% include 'producao_menu.html' %} {% endblock %}

dindri/producao/templates/producao_icone_list.html
<a class="field-form-black" href="{% url object_nome|add:'_detail' item.id %}">
    <span class="icone-link-detalha-ativo glyphicon glyphicon-eye-open"></span>
</a>
{% if item.esta_ativo %}
<a href="{% url object_nome|add:'_update' item.id %}">
    <span class="icone-link-edita-ativo glyphicon glyphicon-pencil"></span>
</a>
{% else %}
<span class="icone-link-edita-inativo glyphicon glyphicon-pencil"></span>
{% endif %}
<a class="icone-link" href="{% url object_nome|add:'_active' item.id %}">
    {% if item.esta_ativo %}
    <span class="icone-link-inativa-ativo glyphicon glyphicon-warning-sign"></span>
    {% else %}
    <span class="icone-link-ativa-ativo glyphicon glyphicon-star-empty"></span>
    {% endif %}
</a>
<a href="{% url object_nome|add:'_delete' item.id %}">
    <span class="icone-link-exclui-ativo glyphicon glyphicon-trash"></span>
</a>
{% if item.tem_restricao %}
<span class="icone-link-restringe-ativo glyphicon glyphicon-ban-circle"></span>
{% endif %}

dindri/producao/templates/sabor_delete_confirm.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block menu %} {% include 'home_menu.html' %} {% endblock %}
{% block titulo %} {% include 'producao.html' %} {% endblock %}
{% block main %}
<h1>Confirmação da exclusão do sabor</h1>
<form method='POST'>
    {% csrf_token %}
    <p>Você tem certeza que deseja excluir o sabor {{object}}</p>
    <button type='submit' class='btn-danger'>Tenho certeza</button>
</form>
{% endblock %}

dindri/producao/templates/sabor_update.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block menu %} {% include 'home_menu.html' %} {% endblock %}
{% block titulo %} {% include 'producao.html' %} {% endblock %}
{% block main %}
<h1>Editar dados do sabor</h1>
<form method='POST'>
    {% csrf_token %}
    {{form|bootstrap}}
    <button type='submit' class='btn btn-success'>Salvar</button>
</form>
{% endblock %}

dindri/producao/templates/tipo_base_delete_confirm.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block javascript %}
<link href="{% static 'css/producao.css' %}" rel="stylesheet">
{% endblock %}
{% block menu %} {% include 'home_menu.html' %} {% endblock %}
{% block titulo %} {% include 'producao.html' %} {% endblock %}
{% block main %}
<h3>Confirmação da exclusão dos dados do tipo de base</h3>
<form class="form-horizontal" method='POST'>
    {% csrf_token %}
    <div class="form-group espaco-medio">
        <div class="col-sm-2">
            <label class="control-form-label" for="id_nome">Nome</label>
        </div>
        <div class="col-sm-10 field-form-black">
            <input type="text" class="control-form" size="50px" readonly="readonly" id="id_nome"
                   value="{{ object.nome }}">
        </div>
    </div>
    <div class="form-group espaco-medio">
        <div class="col-sm-2">
            <label class="control-form-label" for="id_nome">Descrição</label>
        </div>
        <div class="col-sm-10 field-form-black">
            <textarea cols="80" rows="3" class="control-form" id="id_descricao">{{ object.descricao }}</textarea>
        </div>
    </div>
    <div class='form-group espaco-medio'>
        <div class="col-sm-offset-2 col-sm-10">
            <button type='submit' class='btn btn-lg btn-danger botao-esquerdo'>
                <span class="glyphicon glyphicon-remove"></span>
                <span class="texto-botao">Confirma exclusão!</span></button>
            <a class='btn btn-lg btn-primary' href="{% url 'tipo_base_list' %}">
                <span class="glyphicon glyphicon-repeat"></span>
                <span class="texto-botao">Cancelar</span></a>
        </div>
    </div>
</form>
{% endblock %}

dindri/producao/templates/tipo_produto_update.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block javascript %}
<link href="{% static 'css/producao.css' %}" rel="stylesheet">
{% endblock %}
{% block menu %} {% include 'home_menu.html' %} {% endblock %}
{% block titulo %} {% include 'producao.html' %} {% endblock %}
{% block main %}
<h3>Editar dados do tipo de produto</h3>
<form class="form-horizontal" method='POST'>
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group">
        {{ field.errors }}
        <div class="col-sm-2">
            {{ field.label_tag }}
        </div>
        <div class="col-sm-10 field-form-black">
            {{ field }}
        </div>
    </div>
    {% endfor %}
    <div class="form-group espaco-medio">
        <div class='col-sm-offset-2 col-sm-10'>
            <button type='submit' class='btn btn-lg btn-danger'>
                <span class="glyphicon glyphicon-ok"></span>&nbsp;&nbsp;Confirma atualização
            </button>
            <span>&nbsp;&nbsp;&nbsp;</span>
            <a href="{% url 'tipo_produto_list' %}" class='btn btn-lg btn-primary'>
                <span class="glyphicon glyphicon-repeat"></span>&nbsp;&nbsp;Voltar</a>
        </div>
    </div>
</form>
{% endblock %}