dindri/dindri/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from home import views as home_views

urlpatterns = [
   url(r'^$', home_views.home, name='home'),
   url(r'^relacionamento/', include('relacionamento.urls')),
   url(r'^vendas/', include('vendas.urls')),
   url(r'^compras/', include('compras.urls')),
   url(r'^estoque/', include('estoque.urls')),
   url(r'^producao/', include('producao.urls')),
   url(r'^receitas/', include('receitas.urls')),
   url(r'^admin/', admin.site.urls),
]

dindri/home/urls.py
from django.conf.urls import url
from django.contrib import admin
from home import views as home_views

urlpatterns = [
   url(r'^$', home_views.home, name='home_page'),
]

dindri/relacionamento/urls.py
from django.conf.urls import url
from relacionamento.views import RelacionamentoHomeView, \
   ClienteCreateView, ClienteDetailView, ClienteListView, ClienteUpdateView, ClienteDeleteView, \
   ClienteActiveView, ClienteBlockView

urlpatterns = [
   # Relacionamento
   url(r'^$', RelacionamentoHomeView.as_view(), name='relacionamento_home'),
   # Cliente
   url(r'^cliente/lista/$', ClienteListView.as_view(), name='cliente_list'),
   url(r'^cliente/novo/$', ClienteCreateView.as_view(), name='cliente_create'),
   url(r'^cliente/detalha/(?P<pk>\d+)$', ClienteDetailView.as_view(), name='cliente_detail'),
   url(r'^cliente/edita/(?P<pk>\d+)$', ClienteUpdateView.as_view(), name='cliente_update'),
   url(r'^cliente/exclui/(?P<pk>\d+)$', ClienteDeleteView.as_view(), name='cliente_delete'),
   url(r'^cliente/ativa/(?P<pk>\d+)$', ClienteActiveView.as_view(), name='cliente_active'),
   url(r'^cliente/bloqueia/(?P<pk>\d+)$', ClienteBlockView.as_view(), name='cliente_block'),
]

dindri/relacionamento/models.py
from django.db import models
from django.utils import timezone
from utils.models import Seguranca, Endereco

# Create your models here.

SEXO_MASCULINO = 'M'
SEXO_FEMININO = 'F'

SEXO_CHOICES = (
   (SEXO_FEMININO, 'Feminino'),
   (SEXO_MASCULINO, 'Masculino'),
)


class Cliente(Seguranca, Endereco):
   '''Clientes da DinDri Deliciosos'''
   nome = models.CharField(
      max_length=150,
   )
   nome_preferencial = models.CharField(
      max_length=50,
   )
   sexo = models.CharField(
      max_length=1,
      choices=SEXO_CHOICES,
      null=True,
      blank=True,
   )
   endereco = models.TextField(
      max_length=512,
      null=True,
      blank=True,
   )
   watsapp = models.CharField(
      max_length=15,
      null=True,
      blank=True,
   )
   celular = models.CharField(
      max_length=15,
      null=True,
      blank=True,
   )
   fone_residencial = models.CharField(
      max_length=15,
      null=True,
      blank=True,
   )
   interfone = models.CharField(
      max_length=12,
      null=True,
      blank=True,
   )
   email = models.EmailField(
      max_length=256,
      null=True,
      blank=True,
   )
   observacao = models.TextField(
      max_length=512,
      null=True,
      blank=True,
   )
   data_aniversario = models.DateField(
      null=True,
      blank=True,
   )
   responsavel = models.ForeignKey(
      'self',
      on_delete=models.SET_NULL,
      limit_choices_to={'esta_ativo': True},
      null=True,
      blank=True,
   )
   esta_bloqueado = models.BooleanField(
      default=False,
   )
   motivo_bloqueio = models.TextField(
      max_length=1024,
      null=True,
      blank=True,
   )
   bloqueado_em = models.DateTimeField(null=True, blank=True)

   @classmethod
   def is_bloqueado(self):
      return self.esta_bloqueado

   def get_absolute_url(self):
      return 'cliente_list'

   def delete(self, *args, **kwargs):
      self.excluir()
      super(Cliente, self).save(*args, **kwargs)
      return

   def __str__(self):
      return "%i - %s" % (self.id, self.nome_preferencial)

dindri/relacionamento/forms.py
from django import forms
from django.utils import timezone
from relacionamento.models import Cliente, SEXO_CHOICES


class ClienteForm(forms.ModelForm):
   class Meta:
      model = Cliente
      fields = '__all__'


class ClienteCreateUpdateForm(forms.ModelForm):
   class Meta:
      model = Cliente
      fields = (
         'nome',
         'nome_preferencial',
         'endereco',
         'watsapp',
         'celular',
         'fone_residencial',
         'interfone',
         'email',
         'data_aniversario',
         'sexo',
         'responsavel',
         'observacao'
      )
      widgets = {
         'nome': forms.TextInput(attrs={'maxlength': '150', 'size': '80px', 'class': 'control-form'}),
         'nome_preferencial': forms.TextInput(attrs={'maxlength': '50', 'size': '40px', 'class': 'control-form'}),
         'endereco': forms.Textarea(attrs={'cols': '80', 'rows': '3', 'class': 'control-form'}),
         'email': forms.EmailInput(attrs={'maxlength': '150', 'size': '80px', 'class': 'control-form'}),
         'data_aniversario': forms.DateInput(attrs={'type': 'date', 'class': 'control-form'}),
         'sexo': forms.Select(choices=SEXO_CHOICES, attrs={'class': 'control-form'}),
         'observacao': forms.Textarea(attrs={'cols': '80', 'rows': '6', 'class': 'control-form'}),
         'watsapp': forms.TextInput(attrs={'type': 'phone', 'maxlength': '15', 'size': '40px', 'class': 'control-form'})
      }


class ClienteDeleteForm(forms.ModelForm):
   class Meta:
      model = Cliente
      fields = (
         'nome_preferencial',
         'observacao',
         'esta_ativo',
         'esta_excluido',
      )
      widgets = {
         'nome_preferencial': forms.TextInput(attrs={'size': '40px', 'readonly': 'readonly', 'class': 'control-form'}),
         'observacao': forms.Textarea(attrs={'cols': 80, 'rows': 6, 'class': 'control-form'}),
      }


class ClienteDetailForm(forms.ModelForm):
   class Meta:
      model = Cliente
      fields = (
         'nome',
         'nome_preferencial',
         'endereco',
         'watsapp',
         'celular',
         'fone_residencial',
         'interfone',
         'email',
         'data_aniversario',
         'sexo',
         'responsavel',
         'observacao'
      )


class ClienteActiveForm(forms.ModelForm):
   class Meta:
      model = Cliente
      fields = (
         'nome_preferencial',
         'esta_ativo',
         'observacao'
      )
      widgets = {
         'nome_preferencial': forms.TextInput(attrs={'size': '40px', 'readonly': 'readonly', 'class': 'control-form'}),
         'observacao': forms.Textarea(attrs={'cols': 80, 'rows': 6, 'class': 'control-form'}),
      }

   def save(self, commit=True):
      instance = super(ClienteActiveForm, self).save(commit=False)
      instance.esta_ativo = not instance.esta_ativo
      if instance.esta_ativo:
         instance.ativado_em = timezone.now()
      else:
         instance.desativado_em = timezone.now()
      if commit:
         instance.save()
      return instance


class ClienteBlockForm(forms.ModelForm):
   class Meta:
      model = Cliente
      fields = (
         'esta_ativo',
         'esta_bloqueado',
         'nome_preferencial',
         'bloqueado_em',
         'motivo_bloqueio'
      )
      widgets = {
         'nome_preferencial': forms.TextInput(attrs={'size': '40px', 'readonly': 'readonly', 'class': 'control-form'}),
         'motivo_bloqueio': forms.Textarea(
            attrs={'required': 'required', 'cols': '80', 'rows': '6', 'class': 'control-form'}),
      }

   def save(self, commit=True):
      instance = super(ClienteBlockForm, self).save(commit=False)
      instance.esta_ativo = False
      instance.esta_bloqueado = True
      instance.bloqueado_em = timezone.now()
      if commit:
         instance.save()
      return instance

dindri/relacionamento/views.py
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView, TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from relacionamento.models import Cliente
from relacionamento.forms import ClienteDetailForm, ClienteCreateUpdateForm, \
   ClienteDeleteForm, ClienteActiveForm, ClienteBlockForm


# Create your views here.

class RelacionamentoHomeView(TemplateView):
   template_name = 'relacionamento_home.html'


class ClienteListView(ListView):
   model = Cliente
   template_name = 'cliente_list.html'
   fields = [
      'nome_preferencial',
      'endereco',
      'watsapp',
      'interfone',
   ]

   def get_queryset(self):
      qs = super(ClienteListView, self).get_queryset()
      qs = qs.filter(esta_excluido__exact=False, esta_bloqueado__exact=False)
      return qs


class ClienteCreateView(CreateView):
   model = Cliente
   form_class = ClienteCreateUpdateForm
   template_name = 'cliente_create.html'
   success_url = reverse_lazy('cliente_list')


class ClienteDetailView(DetailView):
   model = Cliente
   form_class = ClienteDetailForm
   template_name = 'cliente_detail.html'


class ClienteUpdateView(UpdateView):
   model = Cliente
   form_class = ClienteCreateUpdateForm
   template_name = 'cliente_update.html'
   success_url = reverse_lazy('cliente_list')


class ClienteDeleteView(DeleteView):
   model = Cliente
   form_class = ClienteDeleteForm
   template_name = 'cliente_delete_confirm.html'
   success_url = reverse_lazy('cliente_list')


class ClienteActiveView(UpdateView):
   model = Cliente
   form_class = ClienteActiveForm
   template_name = 'cliente_active.html'
   success_url = reverse_lazy('cliente_list')


class ClienteBlockView(UpdateView):
   model = Cliente
   form_class = ClienteBlockForm
   template_name = 'cliente_block.html'
   success_url = reverse_lazy('cliente_list')

dindri/relacionamento/templates/cliente_active.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block javascript %}
<link href="{% static 'css/relacionamento.css' %}" rel="stylesheet">
{% endblock %}
{% block menu %} {% include 'home_menu.html' %} {% endblock %}
{% block titulo %} {% include 'relacionamento.html' %} {% endblock %}
{% block main %}
{% if form.esta_ativo.value %}
<h3>Confirmação da desativação dos dados do cliente</h3>
{% else %}
<h3>Confirmação da ativação dos dados do cliente</h3>
{% endif %}
<form class="form-horizontal" method='POST'>
    {% csrf_token %}
    <div class="form-group espaco-medio">
        {{ form.nome_preferencial.errors }}
        <div class="col-sm-2">{{ form.nome_preferencial.label_tag }}</div>
        <div class="col-sm-10 field-form-black">{{ form.nome_preferencial }}</div>
    </div>
    <div class="form-group espaco-medio">
        {{ form.observacao.errors }}
        <div class="col-sm-2">{{ form.observacao.label_tag }}</div>
        <div class="col-sm-10 field-form-black">{{ form.observacao }}</div>
    </div>
    {{ form.esta_ativo.as_hidden }}
    <div class='form-group espaco-medio'>
        <div class="col-sm-offset-2 col-sm-10">
            <button type='submit' class='btn btn-lg btn-danger botao-esquerdo'>
                {% if form.esta_ativo.value %}
                <span class="glyphicon glyphicon-remove"></span>&nbsp;&nbsp;
                <span class="texto-botao">Confirma desativação!</span>
                {% else %}
                <span class="glyphicon glyphicon-ok"></span>&nbsp;&nbsp;
                <span class="texto-botao">Confirma ativação!</span>
                {% endif %}
            </button>
            <a href="{% url 'cliente_list' %}" class='btn btn-lg btn-primary'>
                <span class="glyphicon glyphicon-repeat"></span>
                <span class="texto-botao">Cancelar</span></a>
        </div>
    </div>
</form>
{% endblock %}

dindri/relacionamento/templates/cliente_block.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block javascript %}
<link href="{% static 'css/relacionamento.css' %}" rel="stylesheet">
{% endblock %}
{% block menu %} {% include 'home_menu.html' %} {% endblock %}
{% block titulo %} {% include 'relacionamento.html' %} {% endblock %}
{% block main %}
<h1>Confirmação do bloqueio dos dados do cliente</h1>
<form class="form-horizontal" method='POST'>
    {% csrf_token %}
    <div class="form-group espaco-medio">
        {{ form.nome_preferencial.errors }}
        <div class="col-sm-2">
            {{ form.nome_preferencial.label_tag }}
        </div>
        <div class="col-sm-10 field-form-black">{{ form.nome_preferencial }}</div>
    </div>
    <div class="form-group">
        {{ form.motivo_bloqueio.errors }}
        <div class="col-sm-2">
            {{ form.motivo_bloqueio.label_tag }}
        </div>
        <div class="col-sm-10 field-form-black">
            {{ form.motivo_bloqueio }}
        </div>
    </div>
    {{ form.esta_ativo.as_hidden }}
    {{ form.esta_bloqueado.as_hidden }}
    <div class='form-group espaco-medio'>
        <div class="col-sm-offset-2 col-sm-10">
            <button type='submit' class='btn btn-lg btn-danger botao-esquerdo'>
                <span class=" glyphicon glyphicon-lock"></span>
                <span class="texto-botao">Confirma bloqueio!</span>
            </button>
            <a href="{% url 'cliente_list' %}" class='btn btn-lg btn-primary'>
                <span class="glyphicon glyphicon-repeat"></span>
                <span class="texto-botao">Cancelar</span>
            </a>
        </div>
    </div>
</form>
{% endblock %}

dindri/relacionamento/templates/cliente_create.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block javascript %}
<link href="{% static 'css/relacionamento.css' %}" rel="stylesheet">
{% endblock %}
{% block menu %} {% include 'home_menu.html' %} {% endblock %}
{% block titulo %} {% include 'relacionamento.html' %} {% endblock %}
{% block main %}
<h3>Incluir cliente</h3>
<form class="form-horizontal" method='POST'>
    {% csrf_token %}
    {% for item in form %}
    <div class="form-group">
        {{ item.errors }}
        <div class="col-sm-2">
            {{ item.label_tag }}
        </div>
        <div class="col-sm-10 field-form-black">
            {{ item }}
        </div>
    </div>
    {% endfor %}
    <div class="form-group espaco-medio">
        <div class='col-sm-offset-2 col-sm-10'>
            <button type='submit' class='btn btn-lg btn-danger botao-esquerdo'>
                <span class="glyphicon glyphicon-ok"></span>
                <span class="texto-botao">Salvar</span></button>
            <a href="{% url 'cliente_list' %}" class='btn btn-lg btn-primary'>
                <span class="glyphicon glyphicon-repeat"></span>
                <span class="texto-botao">Voltar</span></a>
        </div>
    </div>
</form>
{% endblock %}

dindri/relacionamento/templates/cliente_delete_confirm.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block javascript %}
<link href="{% static 'css/relacionamento.css' %}" rel="stylesheet">
{% endblock %}
{% block menu %} {% include 'home_menu.html' %} {% endblock %}
{% block titulo %} {% include 'relacionamento.html' %} {% endblock %}
{% block main %}
<h3>Confirmação da exclusão dos dados do cliente</h3>
<form class="form-horizontal" method='POST'>
    {% csrf_token %}
    <div class="form-group espaco-medio">
        <label class="col-sm-2" for="id_nome_preferencial">Nome preferencial</label>
        <div class="col-sm-10 field-form-black">
            <input type="text" size="40px" readonly="readonly" id="id_nome_preferencial"
                   value="{{ object.nome_preferencial }}">
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2" for="id_observacao">Observação</label>
        <div class="col-sm-10 field-form-black">
            <textarea rows="3" cols="80" id="id_observacao">{{ object.observacao }}</textarea>
        </div>
    </div>
    <div class='form-group espaco-medio'>
        <div class='col-sm-offset-2 col-sm-10'>
            <button type='submit' class='btn btn-lg btn-danger botao-esquerdo'>
                <span class="glyphicon glyphicon-remove"></span>
                <span class="texto-botao">Confirma exclusão!</span></button>
            <a href="{% url 'cliente_list' %}" class='btn btn-lg btn-primary'>
                <span class="glyphicon glyphicon-repeat"></span>
                <span class="texto-botao">Cancelar</span></a>
        </div>
    </div>
</form>
{% endblock %}

dindri/relacionamento/templates/cliente_detail.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block javascript %}
<link href="{% static 'css/relacionamento.css' %}" rel="stylesheet">
{% endblock %}
{% block menu %} {% include 'home_menu.html' %} {% endblock %}
{% block titulo %} {% include 'relacionamento.html' %} {% endblock %}
{% block main %}
<h3>Detalhes do cliente</h3>
<div class="espaco-medio">
    <div><label class="col-sm-2">Nome</label><label class="col-sm-10 field-form-black">{{object.nome}}</label></div>
    <div><label class="col-sm-2">Nome preferencial</label><label class="col-sm-10 field-form-black">{{object.nome_preferencial}}</label>
    </div>
    <div><label class="col-sm-2">Endereço</label><label class="col-sm-10 field-form-black">{{object.endereco|default_if_none:'---'}}</label>
    </div>
    <div><label class="col-sm-2">Watsapp</label><label class="col-sm-10 field-form-black">{{object.watsapp|default_if_none:'---'}}</label>
    </div>
    <div><label class="col-sm-2">Celular</label><label class="col-sm-10 field-form-black">{{object.celular|default_if_none:'---'}}</label>
    </div>
    <div><label class="col-sm-2">Fone residencial</label><label class="col-sm-10 field-form-black">{{object.fone_residencial|default_if_none:'---'}}</label>
    </div>
    <div><label class="col-sm-2">Interfone</label><label class="col-sm-10 field-form-black">{{object.interfone|default_if_none:'---'}}</label>
    </div>
    <div><label class="col-sm-2">E-Mail</label><label class="col-sm-10 field-form-black">{{object.email|default_if_none:'---'}}</label>
    </div>
    <div><label class="col-sm-2">Data de aniversário</label><label class="col-sm-10 field-form-black">{{object.data_aniversario|default_if_none:'---'}}</label>
    </div>
    <div><label class="col-sm-2">Sexo</label><label class="col-sm-10 field-form-black">{{object.sexo|default_if_none:'---'}}</label>
    </div>
    <div><label class="col-sm-2">Responsável</label><label class="col-sm-10 field-form-black">{{object.responsavel|default_if_none:'---'}}</label>
    </div>
    <div><label class="col-sm-2">Observações</label><label class="col-sm-10 field-form-black">{{object.observacao|default_if_none:'---'}}</label>
    </div>
</div>
<div class="col-sm-offset-2 col-sm-10">
    <a class="btn btn-lg btn-primary botao-esquerdo" href="{% url 'cliente_update' object.id %}">
        <span class="glyphicon glyphicon-pencil"></span>
        <span class="texto-botao">Editar</span></a>
    {% if object.esta_ativo %}
    <a class="btn btn-lg btn-danger botao-esquerdo" href="{% url 'cliente_active' object.id %}">
        <span class="glyphicon glyphicon-warning-sign"></span>
        <span class="texto-botao">Desativar</span></a>
    {% else %}
    <a class="btn btn-lg btn-success botao-esquerdo" href="{% url 'cliente_active' object.id %}">
        <span class="glyphicon glyphicon-star-empty"></span>
        <span class="texto-botao">Ativar</span></a>
    {% endif %}
    <a class="btn btn-lg btn-danger botao-esquerdo" href="{% url 'cliente_delete' object.id %}">
        <span class="glyphicon glyphicon-trash"></span>
        <span class="texto-botao">Excluir</span></a>
    <a class="btn btn-lg btn-danger botao-esquerdo" href="{% url 'cliente_block' object.id %}">
        <span class="glyphicon glyphicon-lock"></span>
        <span class="texto-botao">Bloquear</span></a>
    <a class="btn btn-lg btn-primary botao-esquerdo" href="{% url 'cliente_list' %}">
        <span class="glyphicon glyphicon-repeat"></span>
        <span class="texto-botao">Voltar</span></a>
</div>
{% endblock %}

dindri/relacionamento/templates/cliente_list.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block javascript %}
<link href="{% static 'css/relacionamento.css' %}" rel="stylesheet">
{% endblock %}
{% block menu %} {% include 'home_menu.html' %} {% endblock %}
{% block titulo %} {% include 'relacionamento.html' %} {% endblock %}
{% block main %}
<h3>Lista de Clientes</h3>
<div class='panel-heading panel-success'>
    <a class='btn btn-success btn-lg' href="{% url 'cliente_create' %}">
        <span class="glyphicon glyphicon-plus"></span>
        <span class="texto-botao">Novo Cliente</span>
    </a>
</div>
{% if object_list %}
<div>
    <table class="field-form-black table table-hover">
        <thead>
        <tr>
            <td width="100px">&nbsp;</td>
            <th width="35%">Nome preferencial</th>
            <th width="25%">Endereço</th>
            <th width="15%">Watsapp</th>
            <th width="15%">Interfone</th>
        </tr>
        </thead>
        <tbody>
        {% for cliente in object_list %}
        <tr>
            <td>
                {% if cliente.esta_ativo %}
                <a class="icone-link-ativo" href="{% url 'cliente_update' cliente.id %}">
                    <span class="glyphicon glyphicon-pencil"></span>
                </a>
                {% else %}
                <span class="icone-link-inativo glyphicon glyphicon-pencil"></span>
                {% endif %}
                <span>&nbsp;</span>
                <a class="icone-link-ativo" href="{% url 'cliente_active' cliente.id %}">
                    {% if cliente.esta_ativo %}
                    <span class="glyphicon glyphicon-warning-sign"></span>
                    {% else %}
                    <span class="glyphicon glyphicon-star-empty"></span>
                    {% endif %}
                </a>
                <span>&nbsp;</span>
                <a class="icone-link-ativo" href="{% url 'cliente_block' cliente.id %}">
                    <span class="glyphicon glyphicon-lock"></span>
                </a>
                <span>&nbsp;</span>
                <a href="{% url 'cliente_delete' cliente.id %}">
                    <span class="icone-link-ativo glyphicon glyphicon-trash"></span>
                </a>
            </td>
            <td>
                <a class="field-form-black" href="{% url 'cliente_detail' cliente.id %}">
                    <span>{{cliente.nome_preferencial}}</span>
                </a>
            </td>
            <td>
                <span>{{cliente.endereco}}</span>
            </td>
            <td>
                <span>{{cliente.watsapp}}</span>
            </td>
            <td>
                <span>{{cliente.interfone}}</span>
            <td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% else %}
<div class='alert alert-info'>Não há cliente cadastrado.</div>
{% endif %}

{% endblock %}

dindri/relacionamento/templates/cliente_update.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block javascript %}
<link href="{% static 'css/relacionamento.css' %}" rel="stylesheet">
{% endblock %}
{% block menu %} {% include 'home_menu.html' %} {% endblock %}
{% block titulo %} {% include 'relacionamento.html' %} {% endblock %}
{% block main %}
<h3>Editar dados do cliente</h3>
<form class="form-horizontal" method='POST'>
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group">
        {{ field.errors }}
        <div class="col-sm-2">
            {{ field.label_tag }}
        </div>
        <div class="col-sm-10 field-form-black">
            {{ field }}
        </div>
    </div>
    {% endfor %}
    <div class="form-group espaco-medio">
        <div class='col-sm-offset-2 col-sm-10'>
            <button type='submit' class='btn btn-lg btn-danger botao-esquerdo'>
                <span class="glyphicon glyphicon-ok"></span>
                <span class="texto-botao">Confirma atualização</span></button>
            <a href="{% url 'cliente_list' %}" class='btn btn-lg btn-primary'>
                <span class="glyphicon glyphicon-repeat"></span>
                <span class="texto-botao">Cancelar</span></a>
        </div>
    </div>
</form>
{% endblock %}

dindri/relacionamento/templates/relacionamento.html
Relacionamento

dindri/relacionamento/templates/relacionamento_home.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block javascript %}
<link href="{% static 'css/relacionamento.css' %}" rel="stylesheet">
{% endblock %}
{% block menu %} {% include 'home_menu.html' %} {% endblock %}
{% block titulo %} {% include 'relacionamento.html' %} {% endblock %}
{% block main %} {% include 'relacionamento_menu.html' %} {% endblock %}

dindri/relacionamento/templates/relacionamento_menu.html
<div class="list-group menu-local">
    <a class="list-group-item" href="{% url 'relacionamento_home' %}">Home</a>
    <a class="list-group-item" href="{% url 'cliente_list' %}">Clientes</a>
</div>