dindri/compras/urls.py
from django.conf.urls import url
from django.contrib import admin
from compras.views import ComprasHomeView
from compras.views import CompraListView, CompraDetailView, CompraCreateView
from compras.views import CompraDeleteView, CompraUpdateView, CompraDoneView, CompraCancelView
from compras.views import PedidoListView, PedidoDetailView, PedidoCreateView
from compras.views import PedidoDeleteView, PedidoUpdateView, PedidoActiveView
from compras.views import FornecedorListView, FornecedorDetailView, FornecedorCreateView
from compras.views import FornecedorDeleteView, FornecedorUpdateView, FornecedorActiveView

urlpatterns = [
   # Home
   url(r'^$', ComprasHomeView.as_view(), name='compras_home'),
   # Fornecedor
   url(r'^fornecedor/lista/$', FornecedorListView.as_view(), name='fornecedor_list'),
   url(r'^fornecedor/novo/$', FornecedorCreateView.as_view(), name='fornecedor_create'),
   url(r'^fornecedor/detalha/(?P<pk>\d+)$', FornecedorDetailView.as_view(), name='fornecedor_detail'),
   url(r'^fornecedor/edita/(?P<pk>\d+)$', FornecedorUpdateView.as_view(), name='fornecedor_update'),
   url(r'^fornecedor/exclui/(?P<pk>\d+)$', FornecedorDeleteView.as_view(), name='fornecedor_delete'),
   url(r'^fornecedor/ativa/(?P<pk>\d+)$', FornecedorActiveView.as_view(), name='fornecedor_active'),
   # Compra
   url(r'^compra/lista/$', CompraListView.as_view(), name='compra_list'),
   url(r'^compra/novo/$', CompraCreateView.as_view(), name='compra_create'),
   url(r'^compra/detalha/(?P<pk>\d+)$', CompraDetailView.as_view(), name='compra_detail'),
   url(r'^compra/edita/(?P<pk>\d+)$', CompraUpdateView.as_view(), name='compra_update'),
   url(r'^compra/exclui/(?P<pk>\d+)$', CompraDeleteView.as_view(), name='compra_delete'),
   url(r'^compra/conclui/(?P<pk>\d+)$', CompraDoneView.as_view(), name='compra_done'),
   url(r'^compra/cancela/(?P<pk>\d+)$', CompraCancelView.as_view(), name='compra_cancel'),
   # Pedido
   url(r'^pedido/lista/$', PedidoListView.as_view(), name='pedido_list'),
   url(r'^pedido/novo/$', PedidoCreateView.as_view(), name='pedido_create'),
   url(r'^pedido/detalha/(?P<pk>\d+)$', PedidoDetailView.as_view(), name='pedido_detail'),
   url(r'^pedido/edita/(?P<pk>\d+)$', PedidoUpdateView.as_view(), name='pedido_update'),
   url(r'^pedido/exclui/(?P<pk>\d+)$', PedidoDeleteView.as_view(), name='pedido_delete'),
   url(r'^pedido/ativa/(?P<pk>\d+)$', PedidoActiveView.as_view(), name='pedido_active'),
]

dindri/dindri/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from home import views as home_views

urlpatterns = [
   url(r'^$', home_views.home, name='home'),
   url(r'^relacionamento/', include('relacionamento.urls')),
   url(r'^vendas/', include('vendas.urls')),
   url(r'^compras/', include('compras.urls')),
   url(r'^estoque/', include('estoque.urls')),
   url(r'^producao/', include('producao.urls')),
   url(r'^receitas/', include('receitas.urls')),
   url(r'^admin/', admin.site.urls),
]

dindri/home/urls.py
from django.conf.urls import url
from django.contrib import admin
from home import views as home_views

urlpatterns = [
   url(r'^$', home_views.home, name='home_page'),
]

dindri/compras/models.py
from django.db import models
from django.utils import timezone
from utils.models import Seguranca, Endereco
from estoque.models import Categoria, Item

# Create your models here.

PEDIDO_PENDENTE = 'n'
PEDIDO_ABERTO = 'a'
PEDIDO_FECHADO = 'f'
PEDIDO_CANCELADO = 'c'
PEDIDO_EXCLUIDO = 'e'

SITUACAO_PEDIDO_CHOICES = (
   (PEDIDO_PENDENTE, 'Pedido pendente'),
   (PEDIDO_ABERTO, 'Pedido em aberto'),
   (PEDIDO_FECHADO, 'Pedido fechado'),
   (PEDIDO_CANCELADO, 'Pedido cancelado'),
   (PEDIDO_EXCLUIDO, 'Pedido excluído'),
)

COMPRA_PENDENTE = 'n'
COMPRA_ABERTA = 'a'
COMPRA_FECHADA = 'f'
COMPRA_PARCIAL = 'p'
COMPRA_CANCELADA = 'c'
COMPRA_EXCLUIDA = 'e'

SITUACAO_COMPRA_CHOICES = (
   (COMPRA_PENDENTE, 'Compra pendente'),
   (COMPRA_ABERTA, 'Compra em aberto'),
   (COMPRA_FECHADA, 'Compra fechada'),
   (COMPRA_PARCIAL, 'Compra atendida parcialmente'),
   (COMPRA_CANCELADA, 'Compra cancelada'),
   (COMPRA_EXCLUIDA, 'Compra excluída'),
)

FORNECEDOR_INSUMO = 1
FORNECEDOR_SERVICO = 2
FORNECEDOR_EMBALAGENS = 3

TIPO_FORNECEDOR_CHOICES = {
   (FORNECEDOR_INSUMO, 'Fornecedor de insumos'),
   (FORNECEDOR_SERVICO, 'Fornecedor de serviços'),
   (FORNECEDOR_EMBALAGENS, 'Fornecedor de embalagens'),
}

ITEM_PENDENTE = 'n'
ITEM_ATENDIDO = 'a'
ITEM_CANCELADO = 'c'
ITEM_EXCLUIDO = 'e'

SITUACAO_ITEM_PEDIDO_CHOICES = (
   (ITEM_PENDENTE, 'Item pendente'),
   (ITEM_ATENDIDO, 'Item atendido'),
   (ITEM_CANCELADO, 'Item cancelado'),
   (ITEM_EXCLUIDO, 'Item excluído'),
)

SITUACAO_ITEM_COMPRA_CHOICES = (
   (ITEM_PENDENTE, 'Item pendente'),
   (ITEM_ATENDIDO, 'Item atendido'),
   (ITEM_CANCELADO, 'Item cancelado'),
   (ITEM_EXCLUIDO, 'Item excluído'),
)

class Pedido(Seguranca):
   data_emissao = models.DateField(
      auto_now_add=True,
   )
   data_pedido = models.DateField(
      null=True,
      blank=True,
   )
   data_finalizado = models.DateField(
      null=True,
      blank=True,
   )
   data_limite = models.DateField(
      null=True,
      blank=True,
   )
   situacao_pedido = models.CharField(
      max_length=1,
      choices=SITUACAO_PEDIDO_CHOICES,
      default=PEDIDO_PENDENTE,
   )
   situacao_compra = models.CharField(
      max_length=1,
      choices=SITUACAO_COMPRA_CHOICES,
      default=COMPRA_PENDENTE,
   )
   solicitante = models.CharField(
      max_length=256,
   )
   observacao = models.TextField(
      max_length=1024,
      null=True,
      blank=True,
   )

   def get_situacao_compra_descricao(self):
      for cod, desc in SITUACAO_COMPRA_CHOICES:
         if cod == self.situacao_compra:
            return desc
      return None

   def get_situacao_pedido_descricao(self):
      for cod, desc in SITUACAO_PEDIDO_CHOICES:
         if cod == self.situacao_pedido:
            return desc
      return None

   def __str__(self):
      return "%i - %s - %s" % (self.id, str(self.data_limite), self.solicitante)

class PedidoItem(Seguranca):
   pedido = models.ForeignKey(
      Pedido,
      on_delete=models.CASCADE,
      limit_choices_to={'esta_ativo': True}
   )
   item = models.ForeignKey(
      Categoria,
      on_delete=models.PROTECT,
      limit_choices_to={'esta_ativo': True},
      null=True,
      blank=True,
   )
   descricao = models.TextField(
      max_length=512,
      null=True,
      blank=True,
   )
   quantidade = models.PositiveIntegerField(
      default=0,
   )
   situacao_item = models.CharField(
      max_length=1,
      choices=SITUACAO_ITEM_PEDIDO_CHOICES,
      default=ITEM_PENDENTE,
   )

   def __str__(self):
      return "%s - %i" % (self.tipo_insumo.nome, self.quantidade)

class Fornecedor(Seguranca, Endereco):
   tipo_fornecedor = models.PositiveSmallIntegerField(
      choices=TIPO_FORNECEDOR_CHOICES,
      default=FORNECEDOR_INSUMO,
   )
   nome = models.CharField(
      max_length=256,
   )
   observacao = models.TextField(
      max_length=512,
      null=True,
      blank=True,
   )
   nome_fantasia = models.CharField(
      max_length=128,
      null=True,
      blank=True,
   )
   telefone = models.CharField(
      max_length=18,
      null=True,
      blank=True,
   )
   contato = models.CharField(
      max_length=256,
      null=True,
      blank=True,
   )
   email = models.EmailField(
      max_length=256,
      null=True,
      blank=True,
   )
   cnpj = models.CharField(
      max_length=14,
      null=True,
      blank=True,
   )

   def get_absolute_url(self):
      return 'fornecedor_list'

   def delete(self, *args, **kwargs):
      self.excluir()
      super(Fornecedor, self).save(*args, **kwargs)
      return

   def __str__(self):
      return "%i - %s" % (self.id, self.nome)

class Compra(Seguranca):
   fornecedor = models.ForeignKey(
      Fornecedor,
      on_delete=models.PROTECT,
      limit_choices_to={'esta_ativo': True},
      null=True,
   )
   '''
   pedido = models.ManyToManyField(
      Pedido,
      limit_choices_to={'esta_ativo': True},
      null=True,
   )
   '''
   nota_fiscal = models.CharField(
      max_length=64,
      null=True,
      blank=True,
   )
   data_emissao = models.DateTimeField(
      auto_now_add=True,
   )
   data_compra = models.DateTimeField(
      null=True,
      blank=True,
   )
   valor_total = models.DecimalField(
      max_digits=9,
      decimal_places=2,
      default=0.0,
   )
   situacao_compra = models.CharField(
      max_length=1,
      choices=SITUACAO_COMPRA_CHOICES,
      default=COMPRA_PENDENTE,
   )

   def get_situacao_compra_descricao(self):
      for cod, desc in SITUACAO_COMPRA_CHOICES:
         if cod == self.situacao_compra:
            return desc
      return None

   def cancelar(self):
      self.desativar()
      self.situacao_compra = COMPRA_CANCELADA

   def concluir(self, situacao=COMPRA_FECHADA):
      self.esta_ativo = False
      self.ativado_em = timezone.now()
      self.situacao_compra = situacao

   def remove_valor(self, valor=0):
      self.valor_total = self.valor_total - valor

   def add_valor(self, valor=0):
      self.valor_total = self.valor_total + valor

   def get_absolute_url(self):
      return 'compra_list'

   def save(self, *args, **kwargs):
      #compra = super(Compra, self).save(*args, **kwargs)
      if self.situacao_compra in [COMPRA_FECHADA, COMPRA_PARCIAL]:
         itens = self.compraitem_set.all().exclude(situacao_item__exact=ITEM_CANCELADO)
         self.valort_total = 0
         for item in itens:
            item.situacao_item = ITEM_ATENDIDO
            item.desativar()
            self.valor_total += item.valor_total
            item.save()
      return super(Compra, self).save(*args, **kwargs)

   def delete(self, *args, **kwargs):
      itens = self.compraitem_set.all()
      for item in itens.filter(situacao_item__exact=ITEM_PENDENTE):
         item.delete()
      if itens.filter(situacao_item__exact=ITEM_ATENDIDO).count() == 0:
         self.excluir()
      else:
         self.situacao_compra = COMPRA_PARCIAL
         self.cancelar()
      self.save()

      super(Compra, self).save(*args, **kwargs)
      return

   def __str__(self):
      return "%i - %s - %f" % (self.id, str(self.data_emissao), self.valor_total)

class CompraItem(Seguranca):

   __original = None

   compra = models.ForeignKey(
      Compra,
      on_delete=models.CASCADE,
   )
   item = models.ForeignKey(
      Item,
      on_delete=models.PROTECT,
      limit_choices_to={'esta_ativo': True},
   )
   quantidade = models.PositiveIntegerField(
      default=0,
   )
   valor_unitario = models.DecimalField(
      max_digits=9,
      decimal_places=2,
      default=0.0,
   )
   valor_total = models.DecimalField(
      max_digits=12,
      decimal_places=2,
      default=0.0,
   )
   situacao_item = models.CharField(
      max_length=1,
      choices=SITUACAO_ITEM_COMPRA_CHOICES,
      default=ITEM_PENDENTE,
   )

   def __init__(self, *args, **kwargs):
      super(CompraItem, self).__init__(*args, **kwargs)
      self.__original = self

   def calcule(self):
      self.valor_total = self.valor_unitario * self.quantidade

   def cancelar(self):
      self.desativar()
      self.situacao_item = ITEM_CANCELADO

   def atender(self):
      self.esta_ativo = False
      self.ativado_em = timezone.now()
      self.situacao_item = ITEM_ATENDIDO
      self.item.data_ultima_compra = self.ativado_em
      self.item.quantidade = self.item.quantidade + self.quantidade
      self.item.save()

   def is_cancelado(self):
      return self.situacao_item == ITEM_CANCELADO

   def is_pendente(self):
      return self.situacao_item == ITEM_PENDENTE

   def is_novo(self):
      return self.pk is None

   def is_valor_total_changed(self):
      return self.__original.valor_total != self.valor_total

   def save(self, *args, **kwargs):
      self.calcule()
      if self.is_novo():
         self.compra.add_valor(self.valor_total)
      else:
         if self.__original.esta_aberto:
            if self.is_valor_total_changed():
               self.compra.remove_valor(self._original.valor_total)
               self.compra.add_valor(self.valor_total)
            if self.is_cancelado():
               self.compra.remove_valor(self.valor_total)
            if self.is_pendente():
               self.atender()
      self.compra.save()
      return super(CompraItem, self).save(*args, **kwargs)

   def delete(self, *args, **kwargs):
      if not self.is_ativo():
         self.compra.remove_valor(self.valor_total)
         self.cancelar()
         self.excluir()
         super(CompraItem, self).save(*args, **kwargs)
      return

   def get_absolute_url(self):
      return 'compra_item_list'

   def __str__(self):
      return "%s - %i - %f" % (self.item.nome, self.quantidade, self.valor_total)

dindri/compras/templates/compra_create.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block menu %} {% include 'home_menu.html' %} {% endblock %}
{% block titulo %} {% include 'compras.html' %} {% endblock %}
{% block javascript %}
<link href="{% static 'css/compras.css' %}" rel="stylesheet"/>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="text/javascript">
    $(function() {
        $(".inline.{{ compraitem_form.prefix }}").formset({
            prefix: "{{ compraitem_form.prefix }}",
        })
    })

    function calculate(me){
        id=$(me).attr("id");
        var nomes = id.split("-");
        var prefixo = "#" + nomes[0] + "-" + nomes[1] + "-";
        if (nomes.length == 3) {
            var v = prefixo + "valor_unitario";
            var q = prefixo + "quantidade";
            var t = prefixo + "valor_total";
            $(t).val($(q).val() * $(v).val());
            totalize(nomes[0]);
        }
    }

    function totalize(nome) {
        var indice = 0;
        var st = "#" + nome + "-" + indice + "-valor_total";
        //alert(st);
        var t = 0;
        while ($(st).val() != undefined) {
            t += parseFloat($(st).val());
            alert(t);
            st = "#" + nome + "-" + (++indice) + "-valor_total";
            //alert(indice);
            //alert($(st).val());
            if (indice > 100) {
                break;
            }
        }
        $("#id_valor_total").val(t);
    }
</script>
{% endblock %}
{% block main %}
<div>
    <h3>Incluir compra</h3>
    <form method='POST'>
        {% csrf_token %}
        <legend>Compra</legend>
        {% for item in form %}
        <fieldset>
            <div class="form-group espaco-medio">
                {{ item.errors }}
                <div class="col-sm-2">
                    {{ item.label_tag }}
                </div>
                <div class="col-sm-10 field-form-black">
                    {{ item }}
                </div>
            </div>
        </fieldset>
        {% endfor %}
        <legend>Itens</legend>
        {{ compraitem_form.management_form }}
        {{ compraitem_form.non_form_errors }}
        <fieldset class="espaco-medio">
            <div class="rows {{ compraitem_form.prefix }}">
                <div class="col-sm-4">Item</div>
                <div class="col-sm-8">
                    <div class="col-sm-4">Quantidade</div>
                    <div class="col-sm-4">Valor Unitário</div>
                    <div class="col-sm-4">Valor Total</div>
                </div>
            </div>
        </fieldset>
        {% for item in compraitem_form %}
        <fieldset class="espaco-medio">
            <div class="inline {{ compraitem_form.prefix }}">
                {{ item.id }}
                <div class="col-sm-4">
                {{ item.item.errors }}
                <!--{{ item.item.label_tag }}-->
                {{ item.item }}
                </div>
                <div class="col-sm-8">
                    <div class="col-sm-4">
                    {{ item.quantidade.errors }}
                    <!-- {{ item.quantidade.label_tag }} -->
                    {{ item.quantidade }}
                    </div>
                    <div class="col-sm-4">
                    {{ item.valor_unitario.errors }}
                    <!-- {{ item.valor_unitario.label_tag }} -->
                    {{ item.valor_unitario }}
                    </div>
                    <div class="col-sm-4">
                    {{ item.valor_total.errors }}
                    <!-- {{ item.valor_total.label_tag }} -->
                    {{ item.valor_total }}
                    </div>
                </div>
            </div>
        </fieldset>
        {% endfor %}
        <div class="form-group espaco-medio">
            <div class='col-sm-offset-2 col-sm-10'>
                <button type='submit' class='btn btn-lg btn-danger botao-esquerdo'>
                    <span class="glyphicon glyphicon-ok"></span>
                    <span class="texto-botao">Salvar</span></button>
                <a href="{% url 'compra_list' %}" class='btn btn-lg btn-primary'>
                    <span class="glyphicon glyphicon-repeat"></span>
                    <span class="texto-botao">Voltar</span></a>
            </div>
        </div>
    </form>
</div>
{% endblock %}

dindri/compras/templates/compra_done2.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block menu %} {% include 'home_menu.html' %} {% endblock %}
{% block titulo %} {% include 'compras.html' %} {% endblock %}
{% block javascript %}
<link href="{% static 'css/compras.css' %}" rel="stylesheet"/>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="text/javascript">
    $(function() {
        $(".inline.{{ compraitem_form.prefix }}").formset({
            prefix: "{{ compraitem_form.prefix }}",
        })
    })

    function calculate(me){
        id=$(me).attr("id");
        var nomes = id.split("-");
        var prefixo = "#" + nomes[0] + "-" + nomes[1] + "-";
        if (nomes.length == 3) {
            var v = prefixo + "valor_unitario";
            var q = prefixo + "quantidade";
            var t = prefixo + "valor_total";
            $(t).val($(q).val() * $(v).val());
            totalize(nomes[0]);
        }
    }

    function totalize(nome) {
        var indice = 0;
        var st = "#" + nome + "-" + indice + "-valor_total";
        //alert(st);
        var t = 0;
        while ($(st).val() != undefined) {
            t += parseFloat($(st).val());
            alert(t);
            st = "#" + nome + "-" + (++indice) + "-valor_total";
            //alert(indice);
            //alert($(st).val());
            if (indice > 100) {
                break;
            }
        }
        $("#id_valor_total").val(t);
    }
</script>
{% endblock %}
{% block main %}
<div>
    <h3>Concluir compra</h3>
    <form method='POST'>
        {% csrf_token %}
        <legend>Compra</legend>
        {{ form.errors }}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        {% for item in form.visible_fields %}
        <fieldset class="espaco-medio">
            <div class="rows form-group">
                <div class="col-sm-2">{{ item.label_tag }}</div>
                <div class="col-sm-8 field-form-black">{{ item }}</div>
                <div class="col-sm-2">
                {% if item.errors or item.help_text %}
                    {{ item.errors }}
                    {{ item.help_text }}
                {% else %}
                    <span>&nbsp;</span>
                {% endif %}
                </div>
            </div>
        </fieldset>
        {% endfor %}
        <legend>Itens</legend>
        {{ compraitem_form.management_form }}
        {% if compraitem_form.non_form_errors %}
            {{ compraitem_form.errors }}
        {% endif %}
        {% if compraitem_form.non_form_errors %}
            {{ compraitem_form.non_form_errors }}
        {% endif %}
        <fieldset class="espaco-medio">
            <div class="rows {{ compraitem_form.prefix }}">
                <div class="col-sm-3">Item</div>
                <div class="col-sm-3">Quantidade</div>
                <div class="col-sm-3">Valor Unitário</div>
                <div class="col-sm-3">Valor Total</div>
            </div>
        </fieldset>
        {% for item in compraitem_form %}
        <fieldset class="espaco-medio">
            <div class="rows {{ compraitem_form.prefix }}">
            {% for hidden in item.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in item.visible_fields %}
                {% if not 'DELETE' in field.name %}
                <div class="col-sm-3">
                {{ field.errors }}
                {{ field.help_text }}
                <!-- {{ field.label_tag }} -->
                {{ field }}
                </div>
                {% endif %}
            {% endfor %}
            </div>
        </fieldset>
        {% endfor %}
        <div class="form-group espaco-medio">
            <div class='col-sm-offset-2 col-sm-10'>
                <button type='submit' class='btn btn-lg btn-danger botao-esquerdo'>
                    <span class="glyphicon glyphicon-ok"></span>
                    <span class="texto-botao">Confirma conclusão</span></button>
                <a href="{% url 'compra_list' %}" class='btn btn-lg btn-primary'>
                    <span class="glyphicon glyphicon-repeat"></span>
                    <span class="texto-botao">Voltar</span></a>
            </div>
        </div>
    </form>
</div>
{% endblock %}

dindri/compras/templates/compra_list2.html
{% extends 'base.html' %}
{% block menu %} {% include 'home_menu.html' %} {% endblock %}
{% block titulo %} {% include 'compras.html' %} {% endblock %}
{% block main %}
<h1>Lista de Compras</h1>
<div class='panel-heading panel-success'>
    <a class='btn btn-success btn-lg' href="{% url 'compra_create' %}">
        <span class="glyphicon glyphicon-plus"></span>
        <span class="texto-botao">Nova compra</span>
    </a>
</div>
{% if object_list %}
<div class="panel-group">
    <div class="panel panel-default">
        {% for compra in object_list %}
        <div class="panel-heading">
            <h4 class="panel-title panel-success">
                <a data-toggle="collapse" href="#compra{{compra.id}}">
                    <span class="glyphicon glyphicon-plus"></span>
                </a>
                <a href="{% url 'compra_detail' compra.id %}">{{compra}}</a>
            </h4>
        </div>
        <div id="compra{{compra.id}}" class="panel-collapse collapse">
            {% for detail in compra.compraitem_set.all %}
            <div class="panel-heading panel-info">{{detail}}</div>
            {% empty %}
            <div class="panel-heading panel-danger">Não há itens nesta compra.</div>
            {% endfor %}
        </div>
        {% endfor %}
    </div>
</div>
{% else %}
<div class="alert alert-info">Não há compra cadastrada.</div>
{% endif %}
{% endblock %}

dindri/compras/templates/compra_update.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block menu %} {% include 'home_menu.html' %} {% endblock %}
{% block titulo %} {% include 'compras.html' %} {% endblock %}
{% block javascript %}
<link href="{% static 'css/compras.css' %}" rel="stylesheet"/>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="text/javascript">
    $(function() {
        $(".inline.{{ compraitem_form.prefix }}").formset({
            prefix: "{{ compraitem_form.prefix }}",
        })
    })

    function calculate(me){
        id=$(me).attr("id");
        var nomes = id.split("-");
        var prefixo = "#" + nomes[0] + "-" + nomes[1] + "-";
        if (nomes.length == 3) {
            var v = prefixo + "valor_unitario";
            var q = prefixo + "quantidade";
            var t = prefixo + "valor_total";
            $(t).val($(q).val() * $(v).val());
            totalize(nomes[0]);
        }
    }

    function totalize(nome) {
        var indice = 0;
        var st = "#" + nome + "-" + indice + "-valor_total";
        //alert(st);
        var t = 0;
        while ($(st).val() != undefined) {
            t += parseFloat($(st).val());
            alert(t);
            st = "#" + nome + "-" + (++indice) + "-valor_total";
            //alert(indice);
            //alert($(st).val());
            if (indice > 100) {
                break;
            }
        }
        $("#id_valor_total").val(t);
    }
</script>
{% endblock %}
{% block main %}
<div>
    <h3>Incluir compra</h3>
    <form method='POST'>
        {% csrf_token %}
        <legend>Compra</legend>
        {% for item in form %}
        <fieldset>
            <div class="form-group espaco-medio">
                {{ item.errors }}
                <div class="col-sm-2">{{ item.label_tag }}</div>
                <div class="col-sm-10 field-form-black">{{ item }}</div>
            </div>
        </fieldset>
        {% endfor %}
        <legend>Itens</legend>
        {{ compraitem_form.management_form }}
        {{ compraitem_form.non_form_errors }}
        <fieldset class="espaco-medio">
            <div class="rows {{ compraitem_form.prefix }}">
                <div class="col-sm-3">Item</div>
                <div class="col-sm-3">Quantidade</div>
                <div class="col-sm-3">Valor Unitário</div>
                <div class="col-sm-3">Valor Total</div>
            </div>
        </fieldset>
        {% for item in compraitem_form %}
        <fieldset class="espaco-medio">
            <div class="rows {{ compraitem_form.prefix }}">
                {{ item.id }}
                <div class="col-sm-3">
                {{ item.item.errors }}
                <!--{{ item.item.label_tag }}-->
                {{ item.item }}
                </div>
                <div class="col-sm-3">
                {{ item.quantidade.errors }}
                <!-- {{ item.quantidade.label_tag }} -->
                {{ item.quantidade }}
                </div>
                <div class="col-sm-3">
                {{ item.valor_unitario.errors }}
                <!-- {{ item.valor_unitario.label_tag }} -->
                {{ item.valor_unitario }}
                </div>
                <div class="col-sm-3">
                {{ item.valor_total.errors }}
                <!-- {{ item.valor_total.label_tag }} -->
                {{ item.valor_total }}
                </div>
            </div>
        </fieldset>
        {% endfor %}
        <div class="form-group espaco-medio">
            <div class='col-sm-offset-2 col-sm-10'>
                <button type='submit' class='btn btn-lg btn-danger botao-esquerdo'>
                    <span class="glyphicon glyphicon-ok"></span>
                    <span class="texto-botao">Confirma atualização</span></button>
                <a href="{% url 'compra_list' %}" class='btn btn-lg btn-primary'>
                    <span class="glyphicon glyphicon-repeat"></span>
                    <span class="texto-botao">Voltar</span></a>
            </div>
        </div>
    </form>
</div>
{% endblock %}

dindri/compras/templates/pedido_delete_confirm.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block menu %} {% include 'home_menu.html' %} {% endblock %}
{% block titulo %} {% include 'compras.html' %} {% endblock %}
{% block main %}
<h1>Confirmação da exclusão do pedido</h1>
<form method='POST'>
    {% csrf_token %}
    <p>Você tem certeza que deseja excluir o pedido {{object}}</p>
    <button type='submit' class='btn-danger'>Tenho certeza</button>
</form>
{% endblock %}